'use strict';var aa="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};function m(a,b){if(b){var c=aa;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ba(c,a,{configurable:!0,writable:!0,value:b})}}
function ca(a){function b(b){return a.next(b)}function c(b){return a.throw(b)}return new Promise(function(d,e){function f(a){a.done?d(a.value):Promise.resolve(a.value).then(b,c).then(f,e)}f(a.next())})}m("String.prototype.padStart",function(a){return a?a:function(a,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.padStart must not be null or undefined");a-=this.length;c=void 0!==c?String(c):" ";return(0<a&&c?c.repeat(Math.ceil(a/c.length)).substring(0,a):"")+this}});
m("Array.prototype.includes",function(a){return a?a:function(a,c){var b=this;b instanceof String&&(b=String(b));var e=b.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=b[c];if(f===a||Object.is(f,a))return!0}return!1}});m("Object.values",function(a){return a?a:function(a){var b=[],d;for(d in a)Object.prototype.hasOwnProperty.call(a,d)&&b.push(a[d]);return b}});class p{constructor(a,b,{da:c=!1}={}){this.x=a;this.y=b;this.da=c}};const {min:da,max:ea,floor:fa,pow:ha,log10:ia}=Math;function r(){}function t(a){return a}function u(a,...b){b.forEach(b=>{a.splice(a.indexOf(b),1)})}function v(...a){return Object.assign({},...a)}function ja(a){let b=null;return function(...c){b&&clearTimeout(b);b=setTimeout(function(){b=null;return a(...c)},100)}}function ka(a){let b=null;return function(...c){const d=Date.now();if(!b||100<=d-b)b=d,a(...c)}}
function x(a,b){return a.touches?(a=Array.from(a.touches).find(a=>a.target===b))?a.clientX:NaN:a.clientX}function la(a,b){return a.touches?(a=Array.from(a.touches).find(a=>a.target===b))?a.clientY:NaN:a.clientY}let y;function A(){if("undefined"===typeof y)try{const a={get passive(){y=!0}};window.addEventListener("test",r,a);window.removeEventListener("test",r,a)}catch(a){y=!1}return y}
function B(a="",b){const c=document.createElement("div");a&&a.split(" ").forEach(a=>{c.classList.add(a)});b&&(c.textContent=b);return c}function C(a,b){return 1===b?a:`rgba(${parseInt(a.slice(1,3),16)}, ${parseInt(a.slice(3,5),16)}, ${parseInt(a.slice(5,7),16)}, ${b})`}function D(a,b,c){return ea(da(a,c),b)}function E(a,b,{ua:c=!1}={}){if(c&&a.length)return b(a[a.length-1]);c=NaN;for(let d=0;d<a.length;d++){const e=b(a[d]);if(isNaN(c)||e>c)c=e}return c}
function H(a,b,{ua:c=!1}={}){if(c&&a.length)return b(a[0]);c=NaN;for(let d=0;d<a.length;d++){const e=b(a[d]);if(isNaN(c)||e<c)c=e}return c}function ma(a){return a*a*a*a}function na(a){return-(--a*a*a*a-1)}function oa(a){const b=fa(ia(a));a/=ha(10,b);return(1>a?1:2>a?2:5>a?5:10)*ha(10,b)}function I(a){return"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" ")[a]||"Invalid"}function pa(a){return"Mon Tue Wed Thur Fri Sat Sun".split(" ")[a]||"Invalid"}
function J(a,{Ta:b=!1}={}){const c=a.getHours();a=String(a.getMinutes()).padStart(2,"0");return`${c%12||12}${b?`:${a}`:""} ${12>c?"A":"P"}M`}function K(a){return`${I(a.getMonth())} ${a.getDate()} ${a.getFullYear()}`}const qa={$a:"year",Ya:"month",Ua:"day",Va:"hour",Xa:"minute",Za:"second",Wa:"millisecond"};class L extends Error{constructor(){super("Not implemented")}};const {floor:ra}=Math;function sa(a){return H(a.a,a=>a.x,{ua:!0})}function ta(a){return H(a.a,a=>a.y)}function ua(a){return E(a.a,a=>a.x,{ua:!0})}function va(a){return E(a.a,a=>a.y)}
function wa(a,b,c,{Ba:d="none"}={}){if(!a.a.length)return[];let e;var f=xa(b,a.a,(c,d)=>{d=a.a[d-1];return c>=b&&(!d||d.x<b)});-1===f&&(f=0);const g=a.a.slice(f);e=xa(c,g,(a,b)=>{b=g[b+1];return a<=c&&(!b||b.x>c)});if(-1===e){var h=a.a.length-1;e=c>a.a[h].x?h:f}else e=f+e;h=a.a.slice(f,e+1);if("none"!==d){const g=a.a[f],n=a.a[e];if(g.x!==b&&(f=a.a[f-1])){var k;"linear"===d?k=ya(b,f,g):k=new p(b,f.y,{da:!0});h.unshift(k)}if(n.x!==c&&!(n===g&&g.x>c)&&(k=a.a[e+1])){let a;"linear"===d?a=ya(c,n,k):a=new p(c,
k.y,{da:!0});h.push(a)}}return h}class za{constructor(a,b,c){this.name=a;this.color=b;this.a=c}}function ya(a,b,c){return new p(a,b.y+(c.y-b.y)/(c.x-b.x)*(a-b.x),{da:!0})}function xa(a,b,c){let d=0,e=b.length-1,f=ra((d+e)/2),g;for(;b[f]&&!(g=c(b[f].x,f))&&d<e;)a<b[f].x?e=f-1:d=f+1,f=ra((d+e)/2);return g?f:-1};const {min:Aa,max:Ba}=Math;function Ca(a){throw Error(`Invalid state ${a.I}`);}
class M{constructor({ra:a,duration:b,timing:c,ma:d=r,fa:e=r,X:f=r,Y:g=r,Oa:h=r}){this.f=a;this.g=b;this.o={["linear"]:t,["ease-in"]:ma,["ease-out"]:na}[c];this.l=d;this.j=e;this.i=f;this.m=g;this.h=h;this.c=NaN;this.b=[];this.a=0;this.I="pending"}start(){"active"===this.I&&Ca(this);let a;const b=c=>{a||(a=c);this.a=this.o(Aa(c-a,this.g)/this.g);this.b=this.f.map(a=>{const b=a.K-a.from,c=a.from+b*this.a;return 0<b?Aa(c,a.K):Ba(c,a.K)});this.j(this.b);1>this.a?this.c=requestAnimationFrame(b):(this.I=
"complete",this.i());this.m()};this.c=requestAnimationFrame(b);this.b=this.f.map(a=>a.from);this.I="active";this.l()}stop(){"active"===this.I||Ca(this);cancelAnimationFrame(this.c);this.b=[];this.a=0;this.I="pending";this.h()}};function N(a){return(a.v-a.u[0]-a.u[1])/(a.f-a.a)}function Da(a,b){a.u=b}function Ea(a,b){a.o=b;a.i=NaN;a.a=NaN;a.f=NaN}function Fa(a,b){a.m=b}function Ga(a,b){a.l=b}function Ha(a,b){a.h=b}function Ia(a,b){a.g=b}function Ja(a,{ma:b,fa:c,Y:d,X:e}={}){b&&(a.D=b);c&&(a.C=c);d&&(a.F=d);e&&(a.B=e)}function Ka(a){a.j&&"pending"===a.j.I&&a.j.start()}function La(a){a.j&&a.j.stop()}function O(a){return!isNaN(a.h)&&!isNaN(a.g)}function Ma(a){return a.h===a.g}
class Na{constructor(){this.v=0;this.u=[0,0];this.o=0;this.f=this.a=this.g=this.h=this.l=this.m=this.c=this.i=NaN;this.j=null;this.w=0;this.B=this.F=this.C=this.D=r}A(){throw new L;}b(){throw new L;}W(){return isNaN(this.m)||isNaN(this.l)}G(){throw new L;}clear(){this.c=this.i=this.f=this.a=this.g=this.h=this.l=this.m=NaN}};class Oa extends Na{A(a,{G:b=!1}={}){a=(a-this.u[0])/this.c;return b?D(this.a+a,this.a,this.f):D(a,this.m,this.l)}b(a,{G:b=!1}={}){b&&(a-=this.a);return this.c*a+this.u[0]}G(){const a=isNaN(this.h)?this.m:this.h,b=isNaN(this.g)?this.l:this.g;let c=this.i;if(c){var d=(b-a)/c;d?d>this.o?c*=2:d<this.o-2&&(d=c/2,(b-a)/d<=this.o&&(c=d)):c=NaN}else c=(b-a)/this.o;c?(c!==this.i&&(this.i=c),this.a=a,this.f=b,this.c=N(this)):this.c=this.i=this.f=this.a=NaN}};const {ceil:Pa,floor:Qa}=Math;
class Ra extends Na{constructor({ea:a=!1}={}){super();this.H=a}A(a,{G:b=!1}={}){a=(this.v-this.u[1]-a)/this.c;return b?D(this.a+a,this.a,this.f):D(a,this.m,this.l)}b(a,{G:b=!1}={}){b&&(a-=this.a);return this.v-this.u[1]-this.c*a}G(){var a=isNaN(this.h)?this.m:this.h,b=isNaN(this.g)?this.l:this.g,c=(b-a)/this.o;if(c){var d=a,e=b;if(this.H){c=oa(c);const f=Pa(b/c)-Qa(a/c);f>this.o&&(c=oa(f*c/this.o));d=Qa(a/c)*c;e=Pa(b/c)*c}if(isNaN(this.a)||isNaN(this.f))this.a=d,this.f=e,this.i=c,this.c=N(this);else if(this.j?
(b=this.j.f,a=b[0].K,b=b[1].K):(a=this.a,b=this.f),d!==a||e!==b)this.i=c,this.j?(a=this.j.b,c=a[0],a=a[1]):(c=a,a=b),c={from:c,K:d},a={from:a,K:e},this.j&&this.j.stop(),this.j=new M({timing:"linear",duration:this.w,ra:[c,a],ma:()=>{this.D(d,e)},fa:([a,b])=>{this.a=a;this.f=b;this.c=N(this);this.C(this.j.a)},Y:()=>{this.F()},X:()=>{this.j=null;this.B()}})}else this.c=this.i=this.f=this.a=NaN}};class Sa{constructor(a){this.f=1;this.m=10;this.l="#000000";this.a(a)}a({O:a=NaN,Na:b=NaN,La:c}={}){isNaN(a)||(this.f=a);isNaN(b)||(this.m=b);c&&(this.l=c)}b(){return"linear"}h(){return"ease-out"}i(){return"ease-in"}j(a,b,c){b=b.x-a.x<c.x-b.x?a:c;b.da&&(b=b===a?c:a);return b}pa(a){a=a.map(a=>ta(a));return H(a,t)}oa(a){a=a.map(a=>va(a));return E(a,t)}ja(a){a=a.map(a=>H(a,a=>a.y));return H(a,t)}ia(a){a=a.map(a=>E(a,a=>a.y));return E(a,t)}c(a,b,c,d,{qa:e,la:f}){a.lineCap="round";a.lineJoin="round";a.lineWidth=
this.f;d.forEach(d=>{const g=e(d),k=f(d);a.beginPath();a.strokeStyle=C(d.color,k);g.forEach((d,e)=>{const f=b.b(d.x);d=c.b(d.y);0===e?a.moveTo(f,d):a.lineTo(f,d)});a.stroke()})}g(a,b,c,d,{la:e,ka:f}){a.lineWidth=this.f;d.forEach(d=>{const g=e(d);var k=f(d);if(k){const e=b.b(k.x);k=c.b(k.y);a.fillStyle=C(this.l,g);a.strokeStyle=C(d.color,g);a.beginPath();a.arc(e,k,this.m,0,2*Math.PI);a.fill();a.stroke()}})}};const {round:Ta}=Math;
class Ua{constructor(a){this.f=.5;this.a(a)}a({Ma:a=NaN}={}){isNaN(a)||(this.f=a)}b(){return"neighbor"}h(){return"linear"}i(){return"linear"}j(a){return a}pa(){return 0}oa(a){const b=E(a.map(a=>a.a.length),t),c=[];for(let d=0;d<b;d++)c.push(a.reduce((a,b)=>a+(b.a[d]?b.a[d].y:0),0));return E(c,t)}ja(){return 0}ia(a){const b=E(a.map(a=>a.length),t),c=[];for(let d=0;d<b;d++)c.push(a.reduce((a,b)=>a+(b[d]?b[d].y:0),0));return E(c,t)}c(a,b,c,d,{qa:e,la:f,ka:g}){const h=[];d.forEach(d=>{const k=e(d),n=
f(d),w=g(d);let q;a.fillStyle=w?C(d.color,this.f):d.color;k.forEach((e,f)=>{"undefined"===typeof h[f]&&(h[f]=c.b(0));"undefined"===typeof q&&(q=b.b(e.x));let g=Ta(b.c*((k[f+1]?k[f+1].x:O(b)?b.g:b.l)-e.x));const l=Ta(c.c*e.y)*n,F=q,z=h[f]-l;var G=b.b(e.x);G=Ta(G-F);if(1<=G||-1>=G)g+=G;q+=g;h[f]-=l;if(e=w&&e.x===w.x)a.fillStyle=d.color;a.fillRect(F,z,g,l);e&&(a.fillStyle=C(d.color,this.f))})})}g(){}};class Va{constructor(a){this.a(a)}a(){}b(){return"linear"}h(){return"linear"}i(){return"linear"}j(a,b){return b}pa(a){return a.length?0:NaN}oa(a){return a.length?100:NaN}ja(a){return a.length?0:NaN}ia(a){return a.length?100:NaN}c(a,b,c,d,{qa:e,la:f}){const g=[],h=[],k=[new p(b.f,0),new p(b.a,0)];a.globalCompositeOperation="destination-over";d.forEach(l=>{const n=e(l),w=f(l);a.beginPath();a.fillStyle=l.color;n.forEach((k,l)=>{"undefined"===typeof g[l]&&(g[l]=d.reduce((a,b)=>a+e(b)[l].y*f(b),0));"undefined"===
typeof h[l]&&(h[l]=0);const n=k.y/g[l]*100*w;k=b.b(k.x);const q=c.b(h[l]+n);0===l?a.moveTo(k,q):a.lineTo(k,q);h[l]+=n});k.forEach(d=>{a.lineTo(b.b(d.x),c.b(d.y))});a.fill()})}g(){}};const {min:Wa,max:Xa,floor:Ya}=Math,Za={line:void 0,na:void 0,za:void 0},$a={top:0,right:0,bottom:0,left:0},ab={type:"decimal",count:10,color:"#000000",alpha:1,size:10,font:"Arial, Helvetica, sans-serif"},bb={type:"decimal",count:10,color:"#000000",alpha:1,size:10,font:"Arial, Helvetica, sans-serif",ea:!0},cb={O:1,color:"#000000",alpha:1},db={text:"",color:"#000000",size:10,font:"Arial, Helvetica, sans-serif"};
function eb(a,b){return a.map(a=>{switch(a){case "line":return new Sa(b.line);case "bar":return new Ua(b.na);case "area":return new Va(b.za);default:throw Error(`Unsupported view type ${a}`);}})}function fb(a){return{qa:b=>a.R.get(b),la:b=>a.v.get(b),ka:b=>a.P.get(b)||null}}function gb(a,b){if(!O(a.b))return b.a;const c=a.u.get(b);return wa(b,a.b.h,a.b.g,{Ba:c.b()})}function hb(a){var b=ib(a);const c=b.map(a=>sa(a));b=b.map(a=>ua(a));Fa(a.b,H(c,t));Ga(a.b,E(b,t))}
function jb(a,b){const c=[];Array.from(a.T.entries()).forEach(([a,d])=>{d===b&&c.push(a)});var d=c.map(b=>b.pa(P(a,b))),e=c.map(b=>b.oa(P(a,b)));Fa(b,H(d,t));Ga(b,E(e,t));O(a.b)&&(d=c.map(b=>b.ja(P(a,b))),e=c.map(b=>b.ia(P(a,b))),Ha(b,H(d,t)),Ia(b,E(e,t)))}function kb(a,b){(a=a.A.get(b))&&"active"===a.I&&a.stop()}function lb(a,b){var c=a.u.get(b);const d={from:a.v.get(b),K:1};c=new M({timing:c.h(),duration:250,ra:[d],fa:([c])=>{a.v.set(b,c)},X:()=>{a.A.delete(b)},Y:()=>{a.Z()}});a.A.set(b,c)}
function Q(a,b,c=NaN,d=0){const e=a.o[d];if(!e)throw Error(`Unknown view with index ${d}`);if((d=a.u.get(b))&&d!==e)throw Error("Graph is already added to another view");d=a.B.get(e);if(!isNaN(c)&&d[c]&&d[c]!==b)throw Error(`Index ${c} is already taken`);a.w.includes(b)||a.w.push(b);a.v.has(b)||a.v.set(b,0);d.includes(b)&&delete d[d.indexOf(b)];a.u.set(b,e);a.R.set(b,gb(a,b));isNaN(c)?d.push(b):d[c]=b;hb(a);jb(a,a.T.get(e));kb(a,b);lb(a,b)}
function mb(a){a.w.length=0;a.J.length=0;a.u.clear();a.R.clear();a.v.clear();a.A.clear();a.P.clear();Array.from(a.B.values()).forEach(a=>{a.length=0})}function nb(a){La(a.g);a.c&&La(a.c);Array.from(a.A.values()).forEach(a=>{"active"===a.I&&a.stop()})}
function ob(a,b){var c=a.u.get(b);const d={from:a.v.get(b),K:0};c=new M({timing:c.i(),duration:250,ra:[d],fa:([c])=>{a.v.set(b,c)},X:()=>{var c=a.u.get(b);c=a.B.get(c);u(a.w,b);u(a.J,b);a.u.delete(b);a.R.delete(b);a.v.delete(b);a.A.delete(b);a.P.delete(b);delete c[c.indexOf(b)]},Y:()=>{a.Z()},Oa:()=>{u(a.J,b)}});a.A.set(b,c)}
function pb(a,b){const c=a.u.get(b);if(!a.w.includes(b))throw Error("Unknown graph");a.J.includes(b)||a.J.push(b);hb(a);jb(a,a.T.get(c));a.b.W()?(mb(a),nb(a)):(kb(a,b),ob(a,b))}function qb(a,b,c){const d=P(a,c).map(b=>a.R.get(b)),e=b.h,f=b.g,g=c.ja(d);c=c.ia(d);if(isNaN(e)||g<e)b.h=g;if(isNaN(f)||c>f)b.g=c}function rb(a,b,c){a.b.h=b;a.b.g=c;a.g.h=NaN;a.g.g=NaN;a.c&&(a.c.h=NaN,a.c.g=NaN);a.w.forEach(b=>{a.R.set(b,gb(a,b))});a.o.forEach(b=>{qb(a,a.T.get(b),b)})}
function sb(a,b){a.o.forEach(a=>{a instanceof Sa&&a.a(b.line);a instanceof Ua&&a.a(b.na);a instanceof Va&&a.a(b.za)})}function tb(a,b,c){"x"===b&&(a.j.color=c);"y"===b&&(a.m.color=c);"y-secondary"===b&&(a.l.color=c)}function ub(a,b,c){"x"===b&&(a.j.alpha=c);"y"===b&&(a.m.alpha=c);"y-secondary"===b&&(a.l.alpha=c)}function vb(a){return a.o.map(a=>{if(a instanceof Sa)return"line";if(a instanceof Ua)return"bar";if(a instanceof Va)return"area"})}
function wb(a,b){const c=a.o[b];if(!c)throw Error(`Unknown view index ${b}`);return a.B.get(c)}function R(a,b){return a.b.A(b,{G:!0})}function xb(a){const b=O(a.b);return{start:b?a.b.h:a.b.m,end:b?a.b.g:a.b.l}}function yb(a,b){a.P.clear();isNaN(b)||a.o.forEach(c=>{a.B.get(c).forEach(d=>{var e=R(a,b),f=gb(a,d);const [g]=wa(d,e,e,{Ba:c.b()});e=f.find(a=>a.x>g.x)||g;(f=f[f.indexOf(e)-1])&&e&&a.P.set(d,c.j(f,g,e))})})}
function S(a){const b=a.i.parentNode.offsetWidth,c=a.i.parentNode.offsetHeight;a.D=b;a.S=c;var d=a.b;d.v=b;d.c=N(d);d=a.g;d.v=c;d.c=N(d);a.c&&(d=a.c,d.v=c,d.c=N(d));d=window.devicePixelRatio||1;const e=a.a.g||a.a.b||a.a.c||a.a.f||a.a.a||1,f=Ya(d/e)||1;d!==e?(a.i.width=b*f,a.i.height=c*f,a.i.style.width=`${b}px`,a.i.style.height=`${c}px`):(a.i.width=b,a.i.height=c,a.i.style.width="",a.i.style.height="");a.a.scale(f,f)}
function zb(a){const {W:b,sa:c}=Ab(a.b),{W:d,sa:e}=Ab(a.g);b?(a.h.length=0,a.ca.clear()):c&&Bb(a);d?(a.F.length=0,a.V.clear()):e&&a.ha(a.g);if(a.c){const {W:b,sa:c}=Ab(a.c);b?(a.M.length=0,a.U.clear()):c&&a.ha(a.c)}}function Cb(a){Ka(a.g);a.c&&Ka(a.c);Array.from(a.A.values()).forEach(a=>{"pending"===a.I&&a.start()})}function T(a){zb(a);a.Z();a.$.forEach(a=>a());Cb(a)}
function Db(a){const b=[a.D/2,a.S/2];U(a.a,a.aa.font,a.aa.size);a.a.textBaseline="middle";a.a.textAlign="center";a.a.fillStyle=a.aa.color;a.a.fillText(a.aa.text,...b)}function Eb(a){a.o.forEach(b=>{const c=a.T.get(b),d=a.B.get(b);a.a.save();var e=a.b;a.a.translate(e.c*e.a*-1,c.c*c.a);b.c(a.a,a.b,c,d,a.ya);a.a.restore()})}
function Fb(a){if("none"!==a.m.type||a.c&&"none"!==a.l.type)a.a.save(),a.a.lineWidth=a.H.O,a.F.length?(V(a.a,a.g),a.F.forEach(b=>{let c=a.g.b(b);c+=a.H.O/2;b=Gb(a,b,"y");a.a.strokeStyle=C(a.H.color,b);a.a.beginPath();a.a.moveTo(a.f.left,c);a.a.lineTo(a.D-a.f.right,c);a.a.stroke()})):a.c&&(V(a.a,a.c),a.M.forEach(b=>{let c=a.c.b(b);c+=a.H.O/2;b=Gb(a,b,"y-secondary");a.a.strokeStyle=C(a.H.color,b);a.a.beginPath();a.a.moveTo(a.f.left,c);a.a.lineTo(a.D-a.f.right,c);a.a.stroke()})),a.a.restore()}
function Hb(a){0<a.ba.length&&(a.a.save(),Ib(a.a,a.b),a.a.lineWidth=a.ga.O,a.a.strokeStyle=C(a.ga.color,a.ga.alpha),a.ba.forEach(b=>{b=a.b.b(b);a.a.beginPath();a.a.moveTo(b,a.f.top+a.C.top);a.a.lineTo(b,a.S-(a.f.bottom+a.C.bottom));a.a.stroke()}),a.a.restore())}
function Jb(a){if("none"!==a.j.type){var b=(a.D-a.f.left-a.f.right)/(2*a.b.o);a.a.save();U(a.a,a.j.font,a.j.size);Ib(a.a,a.b);a.a.textAlign=a.h[0]===a.b.m?"start":a.h[a.h.length-1]===a.b.l?"end":"center";a.h.forEach(c=>{const d=a.b.b(c),e=a.S-a.f.bottom-a.j.size/2,f=Kb(a,c,"x");c=Lb(a,c,"x");a.a.fillStyle=C(a.j.color,c);a.a.fillText(f,d,e,b)});a.a.restore()}}
function Mb(a){if("none"!==a.m.type||a.c&&"none"!==a.l.type)a.F.length&&(a.a.save(),U(a.a,a.m.font,a.m.size),V(a.a,a.g),a.a.textAlign="start",a.F.forEach(b=>{let c=a.g.b(b);c-=a.m.size/2;const d=Kb(a,b,"y");b=Lb(a,b,"y");a.a.fillStyle=C(a.m.color,b);a.a.fillText(d,a.f.left,c)}),a.a.restore()),a.c&&a.M.length&&(a.a.save(),U(a.a,a.l.font,a.l.size),V(a.a,a.c),a.a.textAlign="end",a.M.forEach(b=>{let c=a.c.b(b);c-=a.l.size/2;const d=Kb(a,b,"y-secondary");b=Lb(a,b,"y-secondary");a.a.fillStyle=C(a.l.color,
b);a.a.fillText(d,a.D-a.f.right,c)}),a.a.restore())}function Nb(a){a.o.forEach(b=>{const c=a.T.get(b),d=a.B.get(b);a.a.save();var e=a.b;a.a.translate(e.c*e.a*-1,c.c*c.a);b.g(a.a,a.b,c,d,a.ya);a.a.restore()})}function Gb(a,b,c){let d;"y"===c?d=a.V:"y-secondary"===c&&(d=a.U);if(!d)throw Error(`Wrong axis ${c}`);return(d.has(b)?d.get(b):1)*a.H.alpha}
function Kb(a,b,c){if("x"===c)var d=a.j.type;else"y"===c?d=a.m.type:"y-secondary"===c&&(d=a.l.type);if("y-secondary"===c){if(!a.c)throw Error("Y secondary scale is not present");c=a.c}else c="x"===c?a.b:a.g;a=a.xa;if("date"===d){d=c.i;var e;1<=d/31104E6?e="year":1<=d/2592E6?e="month":1<=d/864E5?e="day":1<=d/36E5?e="hour":1<=d/6E4?e="minute":1<=d/1E3&&(e="second");d=a.b.get(e);d.has(b)?b=d.get(b):(c=new Date(b),e="year"===e?`${c.getFullYear()}`:"month"===e?`${c.getFullYear()} ${I(c.getMonth())}`:"day"===
e?`${I(c.getMonth())} ${c.getDate()}`:"hour"===e?`${c.getDate()} ${J(c)}`:"minute"===e?`${J(c,{Ta:!0})}`:"second"===e?`${c.getMinutes()}:${String(c.getSeconds()).padStart(2,"0")}`:"millisecond"===e?`${c.getSeconds()}, ${c.getMilliseconds()}`:c.toString(),d.size===a.c&&d.clear(),d.set(b,e),b=e)}else if("compact"===d)if(a.a.has(b))b=a.a.get(b);else{e=b;for(d=0;1E3<=e;)e/=1E3,d++;e=Number(e.toFixed(1))+["","K","M","B","T"][d];a.a.size===a.c&&a.a.clear();a.a.set(b,e);b=e}else b=String(b);return b}
function Lb(a,b,c){let d;"x"===c?d=a.ca:"y"===c?d=a.V:"y-secondary"===c&&(d=a.U);b=d.has(b)?d.get(b):1;let e;"x"===c?e=a.j.alpha:"y"===c?e=a.m.alpha:"y-secondary"===c&&(e=a.l.alpha);return b*e}function ib(a){return a.w.filter(b=>!a.J.includes(b))}function P(a,b){return a.B.get(b).filter(b=>!a.J.includes(b))}
function Bb(a){const b=a.b.a,c=a.b.f,d=a.b.o,e=a.b.i,f=(a.b.m-b)%e,g=(c-b)/e;a.h.length=0;for(a.h.push(f+b);a.h[a.h.length-1]<c;){const d=f+b+a.h.length*e;if(d>c)break;a.h.push(d)}a.ca.clear();g<d-1&&a.h.slice().forEach(b=>{const f=a.h.indexOf(b),h=b+e/2,n=D(d-1-g,0,1);h<c&&(a.h.splice(f,1,b,h),a.ca.set(h,n))})}
class Ob{constructor(a,b={}){const c=b.L||[],d=v(Za,b.Ca||{}),e=v($a,b.Da||{}),f=v($a,b.Sa||{}),g=v(ab,b.Ea||{}),h=v(bb,b.Ga||{}),k=v(bb,b.Fa||{}),l=v(cb,b.Ka||{}),n=v(cb,b.Qa||{});b=v(db,b.Ha||{});this.i=a;this.a=a.getContext("2d");this.S=this.D=NaN;this.b=new Oa;this.g=new Ra({ea:h.ea});this.c=null;c.some(a=>a.va)&&(this.c=new Ra({ea:k.ea}));this.o=eb(c.map(a=>a.type),d);this.T=new Map(this.o.map((a,b)=>[a,c[b].va?this.c:this.g]));this.B=new Map(this.o.map(a=>[a,[]]));this.ya=fb(this);this.C=e;
this.f=f;this.w=[];this.J=[];this.u=new Map;this.R=new Map;this.v=new Map;this.A=new Map;this.P=new Map;this.h=[];this.j=g;this.ca=new Map;this.F=[];this.m=h;this.V=new Map;this.M=[];this.l=k;this.U=new Map;this.H=l;this.ba=[];this.ga=n;this.aa=b;this.xa=new Pb(1E3);this.$=[];Ea(this.b,this.j.count);Da(this.b,[this.f.left+this.C.left,this.f.right+this.C.right]);Ea(this.g,this.m.count);Da(this.g,[this.f.top+this.C.top,this.f.bottom+this.C.bottom]);this.g.w=250;Ja(this.g,{ma:this.wa.bind(this,this.g),
Y:this.Z.bind(this),X:this.ha.bind(this,this.g)});this.c&&(Ea(this.c,this.l.count),Da(this.c,[this.f.top+this.C.top,this.f.bottom+this.C.bottom]),this.c.w=250,Ja(this.c,{ma:this.wa.bind(this,this.c),Y:this.Z.bind(this),X:this.ha.bind(this,this.c)}))}ka(a){return this.P.get(a)||null}G(){zb(this)}clear(){nb(this);this.b.clear();this.g.clear();this.c&&this.c.clear();mb(this);this.h.length=0;this.ca.clear();this.F.length=0;this.V.clear();this.M.length=0;this.U.clear();Qb(this.xa)}Z(){this.a.clearRect(0,
0,this.D,this.S);this.b.W()||Ma(this.b)?Db(this):(Eb(this),Fb(this),Hb(this),Jb(this),Mb(this),Object.values(this.f).some(a=>0!==a)&&(this.a.save(),this.a.globalCompositeOperation="destination-in",this.a.fillRect(this.f.left,this.f.top,this.D-this.f.left-this.f.right,this.S-this.f.top-this.f.bottom),this.a.restore()),Nb(this))}ha(a){var b=a===this.g;const c=b?this.F:this.M;b=b?this.V:this.U;const d=a.a,e=a.f;a=a.i;c.length=0;for(c.push(d);c[c.length-1]<e;)c.push(d+c.length*a);b.clear()}wa(a,b,c){const d=
a===this.g,e=d?this.F:this.M,f=a.i,g=d?this.V:this.U,h=e.slice(),k=[b];for(;k[k.length-1]<c;)k.push(b+k.length*f);e.length=0;e.push(...Array.from(new Set([...h,...k])).sort((a,b)=>a-b));e.forEach(a=>{g.has(a)||(k.includes(a)&&g.set(a,0),h.includes(a)&&g.set(a,1))});const l=new Map(g);Ja(a,{fa:a=>{e.forEach(b=>{const c=l.get(b);k.includes(b)?g.set(b,Wa(c+a,1)):h.includes(b)&&g.set(b,Xa(c-a,0))})}})}}function Qb(a){a.a.clear();Array.from(a.b.values()).forEach(a=>{a.clear()})}
class Pb{constructor(a){this.c=a;this.b=new Map;this.a=new Map;Object.values(qa).forEach(a=>{this.b.set(a,new Map)})}}function U(a,b,c){b=`${c}px ${b}`;a.font!==b&&(a.font=b)}function Ib(a,b){a.translate(b.c*b.a*-1,0)}function V(a,b){a.translate(0,b.c*b.a)}function Ab(a){const b=a.a,c=a.f;a.G();const d=a.a;a=a.f;return{W:isNaN(d)||isNaN(a),sa:d!==b||a!==c}};const {round:Rb}=Math;
function Sb(a,b){for(;a.a.lastChild;)a.a.removeChild(a.a.lastChild);const c=B("toolbar__column _name"),d=B("toolbar__column _value"),e=B("toolbar__column _percentage");b.forEach(({name:a,value:b,color:h,Pa:k})=>{c.appendChild(B("toolbar__cell",a));a=B("toolbar__cell",Rb(b).toString().replace(/(\d)(?=(\d{3})+(?!\d))/g,"$1 "));d.appendChild(a);"undefined"!==typeof h&&(a.style.color=h);"undefined"!==typeof k&&e.appendChild(B("toolbar__cell",`${String(Number(k.toFixed(1)))}%`))});b=document.createDocumentFragment();
e.firstChild&&b.appendChild(e);b.appendChild(c);b.appendChild(d);a.a.appendChild(b)}class Tb{constructor(a){this.b=a;this.b.classList.add("toolbar");this.c=B("toolbar__title");this.a=B("toolbar__columns");this.b.appendChild(this.c);this.b.appendChild(this.a)}};function Ub(a){a.c.style.display="none"}
function Vb(a,b){if(a.a){var c=a.b,d=a.u;c.$.includes(d)&&u(c.$,d);a.a.removeChild(a.c);a.a.removeEventListener("mousemove",a.h);a.a.removeEventListener("mouseleave",a.v);a.a.removeEventListener("touchmove",a.h);a.a.removeEventListener("touchend",a.w)}a.b=b;c=a.b;d=a.u;c.$.includes(d)||c.$.push(d);a.a=b.i;a.j=a.a.offsetWidth;a.i=a.a.offsetHeight;a.a.parentElement.appendChild(a.c);a.a.addEventListener("mousemove",a.h);a.a.addEventListener("mouseleave",a.v);a.a.addEventListener("touchend",a.w);a.a.addEventListener("touchmove",
a.h,A()&&{passive:!0});Ub(a)}function Wb(a){a.a&&(a.j=a.a.offsetWidth,a.i=a.a.offsetHeight)}function Xb(a){Ub(a);yb(a.b,NaN);a.b.ba.length=0;a.f=!0;T(a.b);a.f=!1;a.g=NaN;a.l=null;cancelAnimationFrame(a.m)}
class Yb{constructor(){this.a=this.b=null;this.i=this.j=NaN;this.c=B();this.A=new Tb(this.c);this.g=NaN;this.l=null;this.f=!1;this.m=NaN;this.C=ka(this.o.bind(this));this.B=ja(this.o.bind(this));this.u=this.D.bind(this);this.h=this.H.bind(this);this.v=this.F.bind(this);this.w=this.J.bind(this)}o(a,b){"date"===this.b.j.type?(a=new Date(a),a=1<=this.b.b.i/864E4?`${pa(a.getDay())}, ${K(a)}`:J(a)):a=String(a);const c=[];b.forEach(({Ra:a,Ja:b})=>{let d;if("bar"===a||"area"===a)d=b.reduce((a,{ta:b})=>a+
b.y,0);b.forEach(({Ia:b,ta:e})=>{c.push({name:b.name,color:b.color,value:e.y,Pa:"area"===a?e.y/d*100:void 0})});"bar"===a&&1<b.length&&c.push({name:"All",value:d})});this.A.c.textContent=a;Sb(this.A,c)}D(){!this.f&&this.g&&Xb(this)}H(a){var b=x(a,this.a);const c=la(a,this.a),d=this.a.getBoundingClientRect(),e=b-d.left,f=c-d.top;if(e!==this.g){b=vb(this.b);var g=[],h=[];yb(this.b,e);b.forEach((a,b)=>{const c=[];wb(this.b,b).forEach(a=>{const b=this.b.ka(a);b&&c.push({Ia:a,ta:b})});c.length&&("line"!==
a&&"area"!==a||c.forEach(({ta:a})=>{g.includes(a.x)||g.push(a.x)}),h.push({Ra:a,Ja:c}))});this.b.ba.length=0;g.forEach(a=>{this.b.ba.push(a)});this.m=requestAnimationFrame(()=>{this.f=!0;T(this.b);this.f=!1;if(h.length){var a=R(this.b,e);this.C(a,h);this.B(a,h);this.c.style.display="block";var b=this.c.offsetHeight;a=D(e-(this.c.offsetWidth+10),0,this.j);b=D(f-b,0,this.i-b);this.c.style.transform=`translate(${a}px, ${b}px)`}else Ub(this)});this.g=e;this.l=a}}F(){Xb(this)}J(){this.l instanceof TouchEvent&&
Xb(this)}};const {max:W}=Math;function Zb(a){a.i=a.a.offsetWidth;a.g=a.u.offsetWidth;a.l=a.v.offsetWidth}function X(a,b){a.h=b;a.j.style.width=`${b}px`}function Y(a,b){a.o=b;a.m.style.width=`${b}px`}function $b(a,b){const c=b<a.i-(a.g+a.l);a.b=b;a.c.style.width=`${b}px`;a.c.classList.toggle("_draggable",c)}function ac(a,b,c){X(a,W(b-a.g,0));Y(a,W(a.i-c-a.l,0));$b(a,W(c-b,0))}function bc(a){const b=a.h+a.g;return{start:b,end:b+a.b}}
class cc{constructor(a){this.a=a;this.i=NaN;this.f=r;this.o=this.l=this.b=this.g=this.h=NaN;this.a.classList.add("zoombar");this.i=this.a.offsetWidth;this.u=B("zoombar__grip _left");this.j=B("zoombar__overlay _left");this.c=B("zoombar__pan");this.v=B("zoombar__grip _right");this.m=B("zoombar__overlay _right");this.a.appendChild(this.j);this.a.appendChild(this.u);this.a.appendChild(this.c);this.a.appendChild(this.v);this.a.appendChild(this.m);dc(this.a,this.u,this.w.bind(this));dc(this.a,this.v,this.F.bind(this));
dc(this.a,this.c,this.D.bind(this),this.C.bind(this),this.B.bind(this));this.j.addEventListener("click",this.A.bind(this));this.m.addEventListener("click",this.H.bind(this))}w(a){a=W(this.b-a,0);const b=this.h-(a-this.b);0<=a&&0<=b&&(X(this,b),$b(this,a),this.f())}F(a){a=W(this.b+a,0);const b=this.o-(a-this.b);0<=a&&0<=b&&(Y(this,b),$b(this,a),this.f())}D(a){let b=this.h+a;a=this.o-a;0>b?(a+=b,b=0):0>a&&(b+=a,a=0);X(this,b);Y(this,a);this.f()}C(){this.c.classList.add("_dragging")}B(){this.c.classList.remove("_dragging")}A(a){const b=
this.j.getBoundingClientRect();a=a.clientX-b.left-this.g;a-=this.b/2;a=W(a,0);X(this,a);Y(this,this.o+b.width-a);this.f()}H(a){const b=this.m.getBoundingClientRect();a=b.right-a.clientX-this.l;a-=this.b/2;a=W(a,0);Y(this,a);X(this,this.h+b.width-a);this.f()}}
function dc(a,b,c=r,d=r,e=r){let f,g,h,k,l;const n=A(),w=c=>{c.preventDefault();c=x(c,b);f=a.getBoundingClientRect();g=b.getBoundingClientRect();h=c-g.left;k=c-f.left;a.addEventListener("mousemove",q);a.addEventListener("mouseup",z);a.addEventListener("mouseleave",z);a.addEventListener("touchend",z);a.addEventListener("touchmove",q,n&&{passive:!1});l&&(clearTimeout(l),l=void 0);a.addEventListener("click",F,!0);d()},q=a=>{a.preventDefault();a=x(a,b)-f.left;if(a>=h&&a+g.width-h<=f.width){const b=a-
k;b&&c(b);k=a}},F=a=>{a.stopPropagation()},z=()=>{a.removeEventListener("mousemove",q);a.removeEventListener("mouseup",z);a.removeEventListener("mouseleave",z);a.removeEventListener("touchmove",q);a.removeEventListener("touchend",z);l=setTimeout(()=>{a.removeEventListener("click",F,!0)},100);k=h=g=f=void 0;e()};b.addEventListener("mousedown",w);b.addEventListener("touchstart",w,n&&{passive:!1})};function ec(a){let b,c;const d=()=>{500>Date.now()-b?(a.N=!a.N,fc(a),a.c()):a.f()};a.a.addEventListener("mousedown",()=>{c||(b=Date.now())});a.a.addEventListener("touchstart",()=>{c=!0;b=Date.now()},A()&&{passive:!0});a.a.addEventListener("mouseup",()=>{c||d();c=!1});a.a.addEventListener("touchend",()=>{d()})}function fc(a){a.a.classList.toggle("_checked",a.N);a.a.classList.toggle("_unchecked",!a.N)}function gc(a,b){a.c=b}function hc(a,b){a.f=b}
class ic{constructor(a,b,c,d=!0){this.a=a;this.g=b;this.b=c;this.N=d;this.f=this.c=r;this.a.classList.add("checkbox");this.a.style.color=this.b;this.a.style.background=this.b;this.a.style.borderColor=this.b;this.a.appendChild(B("checkbox__mark"));this.a.appendChild(B("checkbox__text",this.g));ec(this);fc(this)}};const jc={Ca:{line:{O:2,Na:5},na:{Ma:.5}},Da:{top:15,bottom:25},Sa:{left:10,right:10},Ea:{type:"date",count:6,size:11},Ga:{type:"compact",count:6,size:11},Fa:{type:"compact",count:6,size:11},Ka:{alpha:.1},Qa:{alpha:.1},Ha:{text:"Nothing to show",size:12}},kc={Ca:{line:{O:1}},Da:{top:2,bottom:2,left:10,right:10},Ea:{type:"none"},Ga:{type:"none"},Fa:{type:"none"}};
function lc(a,b){let c,d,e,f,g,h;"line"===a.f&&("day"===b&&(c=e="#8e8e93",d=f=1),"night"===b&&(c=e="#a3b1c2",d=f=.6));"line-double"===a.f&&("day"===b&&(c="#8e8e93",d=1),"night"===b&&(c="#a3b1c2",d=.6),e=a.b[0].color,f=1,g=a.b[1].color,h=1);if("bar"===a.f||"area"===a.f)"day"===b&&(c=e="#252529",d=f=.5),"night"===b&&(c="#a3b1c2",d=.6,e="#ecf2f8",f=.5);c&&tb(a.s,"x",c);d&&ub(a.s,"x",d);e&&tb(a.s,"y",e);f&&ub(a.s,"y",f);g&&tb(a.s,"y-secondary",g);h&&ub(a.s,"y-secondary",h);a.s.H.color={["day"]:"#182d3b",
["night"]:"#ffffff"}[b];a.s.ga.color={["day"]:"#182d3b",["night"]:"#ffffff"}[b];a.s.aa.color={["day"]:"#000000",["night"]:"#ffffff"}[b];sb(a.s,{line:{La:{["day"]:"#ffffff",["night"]:"#242f3e"}[b]}})}
function mc(a){const b=[];a.b.forEach((c,d)=>{const e=B(),f=new ic(e,c.name,c.color);b.push(f);gc(f,()=>{nc(a,{show:f.N?[c]:[],Aa:f.N?[]:[c]})});hc(f,()=>{const e=a.a.w,f=a.b.filter(a=>e.includes(a)&&a!==c);nc(a,{show:e.includes(c)?[]:[c],Aa:f});b.forEach((a,b)=>{a.N=b===d;fc(a)})});a.j.appendChild(e)})}function oc(a){window.addEventListener("resize",a.l.bind(a));window.addEventListener("orientationchange",a.l.bind(a));a.c.f=a.v.bind(a)}
function pc(a){var b=Z;qc.appendChild(a.g);a.b.forEach((b,c)=>{const d="line-double"===a.f?c%2:0;Q(a.s,b,c,d);Q(a.a,b,c,d)});Vb(a.i,a.s);S(a.s);S(a.a);Wb(a.i);Zb(a.c);var c=NaN,d=NaN;const e=a.b[0];for(let a=e.a.length-1;0!==a;a--){const b=e.a[a],f=new Date(b.x);isNaN(d)&&(d=b.x);if(0===a){c=b.x;break}const k=new Date(d);if(f.getDate()===k.getDate()&&f.getMonth()!==k.getMonth()){c=b.x;break}}a.a.G();rb(a.s,c,d);a.s.G();c=a.a.b.b(c,{G:!0});d=a.a.b.b(d,{G:!0});ac(a.c,c,d);lc(a,b);mc(a);a.h();oc(a)}
function nc(a,{show:b=[],Aa:c=[]}={}){b.forEach(b=>{const c=a.b.indexOf(b),d="line-double"===a.f?c%2:0;Q(a.s,b,c,d);Q(a.a,b,c,d)});c.forEach(b=>{pb(a.s,b);pb(a.a,b)});T(a.a);b=bc(a.c);rb(a.s,R(a.a,b.start),R(a.a,b.end));T(a.s);a.h()}
class rc{constructor(a,b,c){const d=B("pane__zoom-chart"),e=v({},jc),f=document.createElement("canvas"),g=B("pane__overview-chart"),h=v({},kc),k=document.createElement("canvas"),l=B("pane__header");a=B("pane__title",a);const n=B("pane__range"),w=B("pane__legend"),q=B();if("line"===c||"line-double"===c)e.L=[{type:"line"}],h.L=[{type:"line"}],"line-double"===c&&(e.L.push({type:"line",va:!0}),h.L.push({type:"line",va:!0}));"bar"===c&&(e.L=[{type:"bar"}],h.L=[{type:"bar"}]);"area"===c&&(e.L=[{type:"area"}],
h.L=[{type:"area"}]);this.b=b;this.f=c;this.g=B("pane");this.s=new Ob(f,e);this.a=new Ob(k,h);this.i=new Yb;this.c=new cc(q);this.m=n;this.j=w;this.u=ka(this.h.bind(this));this.o=ja(this.h.bind(this));d.appendChild(f);g.appendChild(k);g.appendChild(q);l.appendChild(a);l.appendChild(n);this.g.appendChild(l);this.g.appendChild(d);this.g.appendChild(g);this.g.appendChild(this.j)}h(){var a=xb(this.s);if(isNaN(a.start)||isNaN(a.end)||a.start===a.end)this.m.textContent="";else{var b=new Date(a.start),c=
K(b);a=K(new Date(a.end));this.m.textContent=c===a?`${pa(b.getDay())}, ${c}`:`${c} - ${a}`}}l(){S(this.s);T(this.s);S(this.a);T(this.a);Wb(this.i);Zb(this.c);var a=xb(this.s);const b=this.a.b.b(a.start,{G:!0});a=this.a.b.b(a.end,{G:!0});ac(this.c,b||0,a||0)}v(){var a=bc(this.c);const b=R(this.a,a.start);a=R(this.a,a.end);rb(this.s,b,a);this.u();this.o();requestAnimationFrame(()=>{T(this.s)})}};const sc=[],qc=document.querySelector("#panes"),tc=document.querySelector("#theme-switch-button");let Z=window.localStorage.getItem("telegram-contest-chart_theme")||"day",uc;window.addEventListener("scroll",()=>{clearTimeout(uc);document.body.classList.contains("_scrolling")||document.body.classList.add("_scrolling");uc=setTimeout(()=>{document.body.classList.remove("_scrolling")},500)},!1);tc.addEventListener("click",vc);tc.textContent={["day"]:"Switch to Night Mode",["night"]:"Switch to Day Mode"}[Z];
window.addEventListener("load",wc);function xc(){return Promise.all(["1","2","3","4","5"].map(a=>fetch(`data/${a}/overview.json`).then(a=>a.json())))}
function wc(){return ca(function*(){(yield xc()).forEach((a,b)=>{const c=a.columns.find(a=>"x"===a[0]).slice(1),d=a.columns.filter(a=>a[0].startsWith("y")).map(b=>{var [d,...e]=b;return new za(a.names[d],a.colors[d],e.map((a,b)=>new p(c[b],a)))});let e;0===b?e="Line":1===b?e="Dual Axis Line":2===b?e="Stacked Bar":3===b?e="Bar":4===b&&(e="Stacked Area");let f;0===b?f="line":1===b?f="line-double":2===b||3===b?f="bar":4===b&&(f="area");const g=new rc(e,d,f);sc.push(g);pc(g);setTimeout(()=>{T(g.s);T(g.a)},
250*b)});document.body.classList.remove("_loading")}())}function vc(){const a="day"===Z?"night":"day";document.body.classList.remove(`_${Z}`);document.body.classList.add(`_${a}`);window.localStorage.setItem("telegram-contest-chart_theme",Z=a);sc.forEach(b=>{lc(b,a);T(b.s)});tc.textContent={["day"]:"Switch to Night Mode",["night"]:"Switch to Day Mode"}[a]};
