'use strict';var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ba="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function k(a,b){if(b){var c=ba;a=a.split(".");for(var d=0;d<a.length-1;d++){var f=a[d];f in c||(c[f]={});c=c[f]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}}
k("String.prototype.padStart",function(a){return a?a:function(a,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.padStart must not be null or undefined");a-=this.length;c=void 0!==c?String(c):" ";return(0<a&&c?c.repeat(Math.ceil(a/c.length)).substring(0,a):"")+this}});
k("Array.prototype.includes",function(a){return a?a:function(a,c){var b=this;b instanceof String&&(b=String(b));var f=b.length;c=c||0;for(0>c&&(c=Math.max(c+f,0));c<f;c++){var e=b[c];if(e===a||Object.is(e,a))return!0}return!1}});k("Object.values",function(a){return a?a:function(a){var b=[],d;for(d in a)Object.prototype.hasOwnProperty.call(a,d)&&b.push(a[d]);return b}});
k("Promise.prototype.finally",function(a){return a?a:function(a){return this.then(function(b){return Promise.resolve(a()).then(function(){return b})},function(b){return Promise.resolve(a()).then(function(){throw b;})})}});function ca(a,b,c){return new da(b,a.y+(c.y-a.y)/(c.x-a.x)*(b-a.x),{ba:!0})}class da{constructor(a,b,{ba:c=!1}={}){this.x=a;this.y=b;this.ba=c}};const {min:l,max:n,floor:ea,pow:fa,log10:ha}=Math;function p(){}function q(a){return a}function r(a,b){const c=document.createElement("div");a&&c.classList.add(a);b&&(c.textContent=b);return c}function v(a,b){return 1===b?a:`rgba(${parseInt(a.slice(1,3),16)}, ${parseInt(a.slice(3,5),16)}, ${parseInt(a.slice(5,7),16)}, ${b})`}function w(a,b,{ca:c=!1}={}){if(c&&a.length)return b(a[a.length-1]);c=NaN;for(let d=0;d<a.length;d++){const f=b(a[d]);if(isNaN(c)||f>c)c=f}return c}
function x(a,b,{ca:c=!1}={}){if(c&&a.length)return b(a[0]);c=NaN;for(let d=0;d<a.length;d++){const f=b(a[d]);if(isNaN(c)||f<c)c=f}return c}function ia(a){return a*a*a*a}function ja(a){return-(--a*a*a*a-1)}function ka(a){const b=ea(ha(a));a/=fa(10,b);return(1>a?1:2>a?2:5>a?5:10)*fa(10,b)}function z(a){return"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" ")[a]||"Unknown"}
function la(a,{ta:b=!1}={}){const c=a.getHours();a=String(a.getMinutes()).padStart(2,"0");return`${c%12||12}${b?`:${a}`:""} ${12>c?"A":"P"}M`}const ma={Ba:"year",za:"month",wa:"day",xa:"hour",ya:"minute",Aa:"second"};const {floor:na}=Math;function A(a){return{x:x(a.a,a=>a.x,{ca:!0}),y:x(a.a,a=>a.y)}}function B(a){return{x:w(a.a,a=>a.x,{ca:!0}),y:w(a.a,a=>a.y)}}
function C(a,b,c){if(!a.a.length||b===c)return[];var d=oa(b,a.a,(c,d)=>{d=a.a[d-1];return c>=b&&(!d||d.x<b)});-1===d&&(d=0);const f=a.a.slice(d);var e=oa(c,f,(a,b)=>{b=f[b+1];return a<=c&&(!b||b.x>c)});if(-1===e){var g=a.a.length-1;e=c>a.a[g].x?g:d}else e=d+e;g=a.a.slice(d,e+1);const h=a.a[d];h.x!==b&&(d=a.a[d-1])&&g.unshift(ca(d,b,h));d=a.a[e];d.x===c||d===h&&h.x>c||(e=a.a[e+1])&&g.push(ca(d,c,e));return g}class pa{constructor(a,b,c){this.name=a;this.color=b;this.a=c}}
function oa(a,b,c){let d=0,f=b.length-1,e=na((d+f)/2),g;for(;b[e]&&!(g=c(b[e].x,e))&&d<f;)a<b[e].x?f=e-1:d=e+1,e=na((d+f)/2);return g?e:-1};const {min:qa,max:ra}=Math;function D(a){return"active"===a.R}function sa(a){throw Error(`Invalid state ${a.R}`);}
class E{constructor(a,b,c,d=p,f=p,e=p,g=p){this.c=a;this.b=b;this.l={["linear"]:q,["ease-in"]:ia,["ease-out"]:ja}[c];this.i=d;this.h=f;this.j=e;this.g=g;this.f=NaN;this.a=[];this.R="pending"}start(){D(this)&&sa(this);let a;const b=c=>{a||(a=c);const d=qa(c-a,this.b);this.a=this.c.map(a=>{const b=a.J-a.from,c=a.from+b*this.l(d/this.b);return 0<b?qa(c,a.J):ra(c,a.J)});this.i(this.a);d<this.b?this.f=requestAnimationFrame(b):(this.R="complete",this.h());this.j()};this.f=requestAnimationFrame(b);this.a=
this.c.map(a=>a.from);this.R="active"}stop(){D(this)||sa(this);cancelAnimationFrame(this.f);this.R="pending";this.a=[];this.g()}};const {ceil:ta,floor:F,min:ua}=Math;function va(a){const b=new Map;"date"===a&&Object.values(ma).forEach(a=>{b.set(a,new Map)});return b}function G(a){a.a.setTransform(1,0,0,1,0,0);a.a.clearRect(0,0,a.N,a.m);a.a.translate(a.A*a.c*-1,a.B*a.f);a.I===a.H||isNaN(a.j)&&isNaN(a.o)?(a.a.font="20px Arial, Helvetica, Verdana, sans-serif",a.a.textBaseline="middle",a.a.textAlign="center",a.a.fillStyle=a.Y,a.a.fillText(a.ma,a.N/2,a.m/2)):(wa(a),xa(a),ya(a))}
function H(a,b){a.D.includes(b)||a.D.push(b);a.F.has(b)||a.F.set(b,0);var c=isNaN(a.I)||isNaN(a.H)?b.a:C(b,a.I,a.H);a.w.set(b,c);const {x:d,y:f}=A(b);if(isNaN(a.j)||d<a.j)a.j=d;if(isNaN(a.L)||f<a.L)a.L=f;const {x:e,y:g}=B(b);if(isNaN(a.o)||e>a.o)a.o=e;if(isNaN(a.K)||g>a.K)a.K=g;c=x(a.w.get(b),a=>a.y);if(isNaN(a.i)||c<a.i)a.i=c;c=w(a.w.get(b),a=>a.y);if(isNaN(a.h)||c>a.h)a.h=c;c=[{from:a.F.get(b),J:1}];c=new E(c,350,"ease-out",([c])=>{a.F.set(b,c)},()=>{a.G.delete(b)},()=>{G(a)});const h=a.G.get(b);
h&&D(h)&&h.stop();a.G.set(b,c)}function za(a){a.g&&(a.g.stop(),a.g=null);Array.from(a.G.values()).forEach(a=>{D(a)&&a.stop()})}function Aa(a){a.D.length=0;a.M.length=0;a.w.clear();a.F.clear();a.G.clear()}
function Ba(a,b){var c=a.D.filter(c=>c!==b&&!a.M.includes(c)),d=c.map(b=>a.w.get(b));const {x:f,y:e}=A(b);if(f===a.j||e===a.L){var g=c.map(a=>A(a));const b=x(g,({x:a})=>a);b!==a.j&&(a.j=b);g=x(g,({y:a})=>a);g!==a.L&&(a.L=g)}const {x:h,y:m}=B(b);if(h===a.o||m===a.K)c=c.map(a=>B(a)),g=w(c,({x:a})=>a),g!==a.o&&(a.o=g),c=w(c,({y:a})=>a),c!==a.K&&(a.K=c);x(a.w.get(b),a=>a.y)===a.i&&(c=d.map(a=>x(a,a=>a.y)),c=x(c,q),c!==a.i&&(a.i=c));w(a.w.get(b),a=>a.y)===a.h&&(d=d.map(a=>w(a,a=>a.y)),d=w(d,q),d!==a.h&&
(a.h=d));d=[{from:a.F.get(b),J:0}];d=new E(d,350,"ease-in",([c])=>{a.F.set(b,c)},()=>{a.D.splice(a.D.indexOf(b),1);a.M.splice(a.M.indexOf(b),1);a.F.delete(b);a.w.delete(b);a.G.delete(b)},()=>{G(a)},()=>{a.M.splice(a.M.indexOf(b),1)});(c=a.G.get(b))&&D(c)&&c.stop();isNaN(a.j)&&isNaN(a.o)?(za(a),Aa(a)):(a.G.set(b,d),a.M.push(b))}function Ca(a){a.s.length=0;a.T=NaN;a.P.clear();Da(a.ga,a.U);a.b.length=0;a.l.clear();Da(a.ja,a.V)}
function Ea(a){za(a);Aa(a);Ca(a);a.N=NaN;a.m=NaN;a.A=NaN;a.B=NaN;a.j=NaN;a.L=NaN;a.I=NaN;a.i=NaN;a.c=NaN;a.f=NaN;a.o=NaN;a.K=NaN;a.H=NaN;a.h=NaN;a.u=NaN;a.v=NaN}function I(a,b){var c=a.c;return n(l(a.c+(b-a.X)/a.A,a.u),c)}function Fa(a,b){var c=a.f;return n(l(a.f+(a.m-a.O-b)/a.B,a.v),c)}function J(a,b){return a.X+a.A*(b-a.c)}function Ga(){var a=L;return{start:isNaN(a.I)?a.j:a.I,end:isNaN(a.H)?a.o:a.H}}
function Ha(a,b,c){a.I=b;a.H=c;a.i=NaN;a.h=NaN;a.D.forEach(d=>{var f=C(d,b,c);a.w.set(d,f);if(!a.M.includes(d)){d=x(f,a=>a.y);f=w(f,a=>a.y);if(isNaN(a.i)||d<a.i)a.i=d;if(isNaN(a.h)||f>a.h)a.h=f}})}
function M(a,b,c){const d="x"===c?a.U:a.V;var f="x"===c?a.ga:a.ja,e;if("date"===d){a="x"===c?(a.u-a.c)/a.C:(a.v-a.f)/a.b.length;1<=a/31104E6?e="year":1<=a/2592E6?e="month":1<=a/864E5?e="day":1<=a/36E5?e="hour":1<=a/6E4?e="minute":1<=a/1E3&&(e="second");f=f.get(e);if(f.has(b))return f.get(b);a=new Date(b);e="year"===e?`${a.getFullYear()}`:"month"===e?`${a.getFullYear()} ${z(a.getMonth())}`:"day"===e?`${z(a.getMonth())} ${a.getDate()}`:"hour"===e?`${z(a.getMonth())} ${a.getDate()} ${la(a)}`:"minute"===
e?`${la(a,{ta:!0})}`:"second"===e?`${a.getMinutes()}:${String(a.getSeconds()).padStart(2,"0")}`:a.toString();1E3===f.size&&f.clear();f.set(b,e)}else{if(f.has(b))return f.get(b);if("compact"===d){e=b;for(a=0;1E3<=e;)e/=1E3,a++;e=Number(e.toFixed(1))+["","K","M","B","T"][a]}else e=String(b);1E3===f.size&&f.clear();f.set(b,e)}return e}function Ia(a){a.A=(a.N-a.X-a.na)/(a.u-a.c)}function O(a){a.B=(a.m-a.ia-a.O)/(a.v-a.f)}
function Ja(a){var b=isNaN(a.I)?a.j:a.I,c=isNaN(a.H)?a.o:a.H;let d=a.T;if(d){const e=(c-b)/d;e?e>a.C?d*=2:e<a.C-2&&(d/=2):d=NaN}else d=(c-b)/a.C;if(d){a.c=b;a.u=c;Ia(a);a.T!==d&&(a.T=d,a.P.clear());b=(a.j-a.c)%d;var f=(a.u-a.c)/d;for(a.s=[a.c+b];a.s[a.s.length-1]<a.u+b;)c=a.c+b+a.s.length*d,a.s.push(c),a.P.delete(c);f<a.C-1&&a.s.slice().forEach(b=>{const c=b+d/2;c<a.u&&(a.s.splice(a.s.indexOf(b),1,b,c),a.P.set(c,a.C-1-f))})}else a.c=NaN,a.u=NaN,a.A=NaN,a.s=[],a.T=NaN,a.P.clear()}
function Ka(a){var b=isNaN(a.i)?a.L:a.i,c=isNaN(a.h)?a.K:a.h;let d=(c-b)/a.C;if(d){var f="nice"===a.ra;if(f){d=ka(d);const e=ta(c/d)-F(b/d);e>a.C&&(d=ka(e*d/a.C))}var e=f?F(b/d)*d:b,g=f?ta(c/d)*d:c;if(isNaN(a.f)||isNaN(a.v))for(a.f=e,a.v=g,O(a),a.b=[a.f];a.b[a.b.length-1]<a.v;)a.b.push(a.f+a.b.length*d);else if(f=a.g&&a.g.c,b=a.g&&a.g.a,c=f?f[0].J:a.f,f=f?f[1].J:a.v,e!==c||g!==f){for(var h=a.b.slice(),m=[e];m[m.length-1]<g;)m.push(e+m.length*d);a.b=Array.from(new Set([...h,...m])).sort((a,b)=>a-b);
a.b.forEach(b=>{a.l.has(b)||(m.includes(b)&&a.l.set(b,0),h.includes(b)&&a.l.set(b,1))});var t=new Map(a.l);b=[{from:b?b[0]:c,J:e},{from:b?b[1]:f,J:g},{from:0,J:1}];a.g&&a.g.stop();a.g=new E(b,350,"linear",([b,c,d])=>{a.f=b;a.v=c;O(a);a.b.forEach(b=>{const c=t.get(b);m.includes(b)?a.l.set(b,c+d):h.includes(b)&&a.l.set(b,c-d)})},()=>{a.g=null;a.l.clear();for(a.b=[e];a.b[a.b.length-1]<g;)a.b.push(e+a.b.length*d)},()=>{G(a)})}}else a.f=NaN,a.v=NaN,a.B=NaN,a.b=[],a.l.clear()}
function P(a){Ja(a);Ka(a);a.g&&"pending"===a.g.R&&a.g.start();Array.from(a.G.values()).forEach(a=>{"pending"===a.R&&a.start()});G(a)}function wa(a){a.a.lineWidth=1;if("none"!==a.V){const b=a.A*a.c;a.b.forEach(c=>{const d=a.m-a.O-a.B*c;c=a.l.has(c)?a.l.get(c):1;a.a.strokeStyle=v(a.ha,c);a.a.beginPath();a.a.moveTo(b,d);a.a.lineTo(b+a.N,d);a.a.stroke()})}}
function xa(a){a.a.lineCap="round";a.a.lineJoin="round";a.a.lineWidth=a.W;a.D.forEach(b=>{const c=a.F.get(b),d=a.w.get(b);let f;a.a.beginPath();d.forEach((b,c)=>{const d=a.X+a.A*b.x;b=a.m-a.O-a.B*b.y;f&&F(f)===F(d)||(0===c?a.a.moveTo(d,b):a.a.lineTo(d,b),f=d)});a.a.strokeStyle=v(b.color,c);a.a.stroke()})}
function ya(a){a.a.font="15px Arial, Helvetica, Verdana, sans-serif";if("none"!==a.U){const b=a.m-a.B*a.f-10,c=a.N/a.s.length,d=a.c===a.j,f=a.u===a.o;a.s.forEach(e=>{const g=a.A*e,h=M(a,e,"x");e=a.P.has(e)?a.P.get(e):1;a.a.textAlign=d?"start":f?"end":"center";if(a.oa){const d=Array(h.length).fill("\u2588").join(""),e=a.a.measureText(h).width;a.a.fillStyle=a.Z;a.a.fillText(d,g,b,ua(e,c))}a.a.fillStyle=v(a.Y,e);a.a.fillText(h,g,b,c)})}if("none"!==a.V){const b=a.A*a.c;a.b.forEach(c=>{const d=a.m-a.O-
a.B*c-10,f=M(a,c,"y");c=a.l.has(c)?a.l.get(c):1;a.a.textAlign="start";if(a.pa){const e=Array(f.length).fill("\u2588").join(""),g=a.a.measureText(f).width;a.a.fillStyle=v(a.Z,c);a.a.fillText(e,b,d,g)}a.a.fillStyle=v(a.Y,c);a.a.fillText(f,b,d)})}}function Da(a,b){"date"===b?Array.from(a.keys()).forEach(b=>{a.get(b).clear()}):a.clear()}
class La{constructor(a,{ea:b="decimal",Fa:c=!1,fa:d="decimal",va:f="extremum",ua:e=!1,da:g=0,$:h=0,ka:m=0,la:t=0,aa:K=1,sa:y=10,Da:N="#000000",Ea:u="#000000",Ca:ab="#000000",qa:bb=""}={}){this.S=a;this.a=a.getContext("2d");this.ia=g;this.O=h;this.X=m;this.na=t;this.W=K;this.C=y;this.ha=N;this.Y=u;this.Z=ab;this.ma=bb;this.D=[];this.M=[];this.w=new Map;this.F=new Map;this.G=new Map;this.s=[];this.U=b;this.oa=c;this.T=NaN;this.P=new Map;this.ga=va(this.U);this.b=[];this.V=d;this.ra=f;this.pa=e;this.l=
new Map;this.ja=va(this.V);this.g=null;this.v=this.u=this.h=this.H=this.K=this.o=this.f=this.c=this.i=this.I=this.L=this.j=this.B=this.A=this.m=this.N=NaN}resize(){this.N=this.S.parentNode.offsetWidth;this.m=this.S.parentNode.offsetHeight;this.S.width=this.N;this.S.height=this.m;Ia(this);O(this)}};function Ma(a,b){for(;a.a.firstChild;)a.a.removeChild(a.a.firstChild);b.forEach(({title:b,value:d,color:f})=>{const c=r("label__item");d=r("label__item-value",d);b=r("label__item-title",b);c.style.color=f;c.appendChild(d);c.appendChild(b);a.a.appendChild(c)})}class Na{constructor(a){this.b=a;this.b.classList.add("label");this.c=r("label__title");this.a=r("label__items");this.b.appendChild(this.c);this.b.appendChild(this.a)}};const {abs:Oa}=Math;function Pa(){var a=Q,b=L;a.a&&(a.a.removeEventListener("mousemove",a.o),a.a.removeEventListener("mouseleave",a.m),a.a.removeEventListener("touchstart",a.s));a.a=b.S.parentElement;a.c=a.a.getBoundingClientRect();a.a.addEventListener("mousemove",a.o);a.a.addEventListener("mouseleave",a.m);a.a.addEventListener("touchstart",a.s);a.b=b}function Qa(a){a.h.forEach(b=>{a.a.removeChild(b)});a.h.length=0}
function R(a){a.h.length&&(Qa(a),a.a.contains(a.g)&&a.a.removeChild(a.g),a.a.contains(a.f)&&a.a.removeChild(a.f))}function Ra(a,b){const c=a.b.ia,d=a.b.O;a.g.style.left=`${b}px`;a.g.style.top=`${c}px`;a.g.style.height=`${a.c.height-c-d}px`;a.a.appendChild(a.g)}
function Sa(a,b,c,d){c="date"===a.b.U?(new Date(c.x)).toLocaleDateString("en-us",{weekday:"short",month:"short",day:"numeric",hour:"numeric",minute:"numeric"}):M(a.b,c.x,"x");d=Array.from(d.entries()).sort((a,b)=>b[1].y-a[1].y).map(([b,c])=>({title:b.name,color:b.color,value:M(a.b,c.y,"y")}));a.j.c.textContent=c;Ma(a.j,d);a.a.appendChild(a.f);d=a.c.width;c=a.f.offsetWidth;b=b+c+10<=d?b+10:c+10<=b?b-c-10:n(l(b-c/2,d),0);a.f.style.left=`${b}px`}
class Ta{constructor(){this.b=this.c=this.a=null;this.h=[];this.g=r("cursor__ruler");this.f=r();this.j=new Na(this.f);this.l=this.i=NaN;this.o=this.v.bind(this);this.m=this.u.bind(this);this.s=this.w.bind(this)}resize(){this.a&&(this.c=this.a.getBoundingClientRect())}v(a){const b=Date.now();if(!(100>b-this.l)){var c=a.clientX-this.c.left;a=a.clientY-this.c.top;var d=this.i||this.b.W,f=I(this.b,c-d),e=I(this.b,c+d),g=Fa(this.b,a),h=new Map;this.b.D.forEach(a=>{const b=C(a,f,e).find(a=>!a.ba);b&&h.set(a,
b)});if(h.size){R(this);let a;Array.from(h.entries()).forEach(([b,c])=>{{const a=r("cursor__marker");a.style.borderColor=b.color;a.style.left=`${J(this.b,c.x)}px`;b=this.b;a.style.top=`${b.m-b.O-b.B*(c.y-b.f)}px`;this.a.appendChild(a);this.h.push(a)}if(!a||Oa(g-c.y)<Oa(g-a.y))a=c});c=J(this.b,a.x);Ra(this,c);Sa(this,c,a,h)}this.i=NaN;this.l=b}}w(a){const b=this.b.S;if(a=Array.from(a.touches).find(a=>a.target===b))this.i=a.radiusX||NaN}u(){R(this)}};const {max:Ua,round:Va}=Math;function S(a,b){a.h=b;a.j.style.width=`${b}px`}function T(a,b){a.o=b;a.m.style.width=`${b}px`}function Wa(a,b){const c=b<a.i-(a.g+a.l);a.f=b;a.c.style.width=`${b}px`;a.c.classList.toggle("_draggable",c)}function Xa(a,b){var c=U;S(c,a-c.g);T(c,c.i-b-c.l);Wa(c,b-a)}function Ya(){var a=U;const b=a.h+a.g;return{start:b,end:b+a.f}}
class Za{constructor(a){this.a=a;this.i=NaN;this.b=p;this.o=this.l=this.f=this.g=this.h=NaN;this.a.classList.add("zoombar");this.i=this.a.offsetWidth;this.s=r("zoombar__grip");this.j=r("zoombar__overlay");this.c=r("zoombar__pan");this.u=r("zoombar__grip");this.m=r("zoombar__overlay");this.a.appendChild(this.j);this.a.appendChild(this.s);this.a.appendChild(this.c);this.a.appendChild(this.u);this.a.appendChild(this.m);this.g=this.s.offsetWidth;this.l=this.u.offsetWidth;$a(this.a,this.s,this.v.bind(this));
$a(this.a,this.u,this.D.bind(this));$a(this.a,this.c,this.C.bind(this),this.B.bind(this),this.A.bind(this));this.j.addEventListener("click",this.w.bind(this));this.m.addEventListener("click",this.F.bind(this))}resize(){this.i=this.a.offsetWidth}v(a){const b=this.f-a;0<=b&&(S(this,this.h+a),Wa(this,b),this.b())}D(a){const b=this.f+a;0<=b&&(T(this,this.o-a),Wa(this,b),this.b())}C(a){let b=this.h+a;a=this.o-a;0>b?(a+=b,b=0):0>a&&(b+=a,a=0);S(this,b);T(this,a);this.b()}B(){this.c.classList.add("_dragging")}A(){this.c.classList.remove("_dragging")}w(a){const b=
this.j.getBoundingClientRect();a=a.clientX-b.left-this.g;a-=this.f/2;a=Ua(a,0);S(this,a);T(this,this.o+b.width-a);this.b()}F(a){const b=this.m.getBoundingClientRect();a=b.right-a.clientX-this.l;a-=this.f/2;a=Ua(a,0);T(this,a);S(this,this.h+b.width-a);this.b()}}function cb(a,b){return a.touches?(a=Array.from(a.touches).find(a=>a.target===b))?a.clientX:NaN:a.clientX}
function $a(a,b,c=p,d=p,f=p){let e,g,h,m,t;const K=c=>{c=cb(c,b);e=a.getBoundingClientRect();g=b.getBoundingClientRect();h=c-g.left;m=c-e.left;a.addEventListener("mousemove",y);a.addEventListener("touchmove",y);a.addEventListener("mouseup",u);a.addEventListener("mouseleave",u);a.addEventListener("touchend",u);t&&(clearTimeout(t),t=void 0);a.addEventListener("click",N,!0);d()},y=a=>{a=cb(a,b)-e.left;if(a>=h&&a+g.width-h<=e.width){const b=a-m;b&&c(Va(b));m=a}},N=a=>{a.stopPropagation()},u=()=>{a.removeEventListener("mousemove",
y);a.removeEventListener("touchmove",y);a.removeEventListener("mouseup",u);a.removeEventListener("mouseleave",u);a.removeEventListener("touchend",u);t=setTimeout(()=>{a.removeEventListener("click",N,!0)},100);m=h=g=e=void 0;f()};b.addEventListener("mousedown",K);b.addEventListener("touchstart",K)};function db(a){a.c.addEventListener("click",()=>{a.b=!a.b;a.a.classList.add("_animated");eb(a);a.f()})}function eb(a){a.a.classList.toggle("_checked",a.b);a.a.classList.toggle("_unchecked",!a.b)}function fb(a,b){a.f=b}
class gb{constructor(a,b,c,d=!0){this.a=a;this.h=b;this.g=c;this.b=d;this.f=p;this.a.classList.add("checkbox");this.c=r("checkbox__icon");this.c.style.borderColor=this.g;this.c.appendChild(r("checkbox__mark"));this.a.appendChild(this.c);this.a.appendChild(r("checkbox__text",this.h));db(this);eb(this)}};const V=window.matchMedia("only screen and (max-width: 480px) and (orientation: portrait)"),L=new La(document.querySelector("#zoom-chart-canvas"),{ea:"date",fa:"compact",va:"nice",ua:!0,da:30,$:40,sa:V.matches?3:5,aa:V.matches?2:3,qa:"No data"}),W=new La(document.querySelector("#overview-chart-canvas"),{ea:"none",fa:"none",da:10,$:10,ka:15,la:15,aa:V.matches?1:2}),Q=new Ta,hb=document.querySelector("#zoombar"),U=new Za(hb),ib=document.querySelector("#title"),X=document.querySelector("#legend"),jb=
document.querySelector("#select"),kb=document.querySelector("#theme-switch-button"),lb=document.querySelector("#repo-link"),Y=[],mb=[];let Z=window.localStorage.getItem("telegram-contest-chart_theme")||"day";
window.addEventListener("load",()=>{fetch("data.json").then(a=>a.json()).then(a=>{a.forEach(a=>{const b=a.columns.find(a=>"x"===a[0]).slice(1),d=a.columns.filter(a=>a[0].startsWith("y")).map(([c,...d])=>new pa(a.names[c],a.colors[c],d.map((a,c)=>new da(b[c],a))));Y.push(d)})}).finally(()=>{Pa();U.b=nb;kb.addEventListener("click",()=>{ob("day"===Z?"night":"day")});V.addListener(()=>{var a=L;a.C=V.matches?3:5;a.c=NaN;a.f=NaN;a.u=NaN;a.v=NaN;Ca(a);L.W=V.matches?2:3;W.W=V.matches?1:2;pb()});window.addEventListener("resize",
pb);window.addEventListener("orientationchange",pb);Y.forEach(a=>{const b=r("select__chart"),c=document.createElement("canvas"),d=new La(c,{ea:"none",fa:"none",da:5,$:5,ka:5,la:5,aa:1});a.forEach(a=>{H(d,a)});b.appendChild(c);b.addEventListener("click",()=>qb(a));jb.appendChild(b);mb.push(d)});mb.forEach(a=>{a.resize();P(a)});ob(Z);Y[0]&&qb(Y[0]);lb.textContent="https://github.com/kirilldronkin/telegram-contest-chart"})});
function ob(a){document.body.classList.remove(`_${Z}`);document.body.classList.add(`_${a}`);window.localStorage.setItem("telegram-contest-chart_theme",Z=a);kb.textContent={["day"]:"Switch to Night Mode",["night"]:"Switch to Day Mode"}[a];L.ha={["day"]:"#dfe7eb",["night"]:"#394959"}[a];L.Y={["day"]:"#a9b3b9",["night"]:"#4c5f6f"}[a];L.Z={["day"]:"#ffffff",["night"]:"#232f3d"}[a];P(L)}
function qb(a){R(Q);Ea(L);for(Ea(W);X.firstChild;)X.removeChild(X.firstChild);a.forEach(a=>{const b=r(),c=new gb(b,a.name,a.color);fb(c,()=>{c.b?(H(L,a),H(W,a)):(Ba(L,a),Ba(W,a));P(W);const b=Ya();Ha(L,I(W,b.start),I(W,b.end));P(L)});H(L,a);H(W,a);X.appendChild(b)});L.resize();P(L);W.resize();P(W);Xa(15,hb.offsetWidth-15);const b=Y.indexOf(a);Array.from(jb.childNodes).forEach((a,d)=>{a.classList.toggle("_active",d===b)});ib.textContent=`Chart #${b+1}`}
function pb(){[L,W,...mb].forEach(a=>{a.resize();P(a)});R(Q);Q.resize();var a=Ga();const b=J(W,a.start);a=J(W,a.end);U.resize();Xa(b,a)}function nb(){var a=Ya();const b=I(W,a.start);a=I(W,a.end);Ha(L,b,a);P(L);R(Q)};
