'use strict';var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ba="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function k(a,b){if(b){var c=ba;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&aa(c,a,{configurable:!0,writable:!0,value:b})}}
k("String.prototype.padStart",function(a){return a?a:function(a,c){if(null==this)throw new TypeError("The 'this' value for String.prototype.padStart must not be null or undefined");a-=this.length;c=void 0!==c?String(c):" ";return(0<a&&c?c.repeat(Math.ceil(a/c.length)).substring(0,a):"")+this}});
k("Array.prototype.includes",function(a){return a?a:function(a,c){var b=this;b instanceof String&&(b=String(b));var e=b.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=b[c];if(f===a||Object.is(f,a))return!0}return!1}});k("Promise.prototype.finally",function(a){return a?a:function(a){return this.then(function(b){return Promise.resolve(a()).then(function(){return b})},function(b){return Promise.resolve(a()).then(function(){throw b;})})}});
function ca(a,b,c){return new da(b,a.y+(c.y-a.y)/(c.x-a.x)*(b-a.x),{ca:!0})}class da{constructor(a,b,{ca:c=!1}={}){this.x=a;this.y=b;this.ca=c}};const {min:l,max:n,floor:ea,pow:fa,log10:ha}=Math;function p(){}function q(a){return a}function r(a,b){const c=document.createElement("div");a&&c.classList.add(a);b&&(c.textContent=b);return c}function v(a,b){return 1===b?a:`rgba(${parseInt(a.slice(1,3),16)}, ${parseInt(a.slice(3,5),16)}, ${parseInt(a.slice(5,7),16)}, ${b})`}function ia(a,b,c){return a.reduce((a,e)=>{e=b(e);return isNaN(e)||isNaN(a)?e:c(a,e)},NaN)}function w(a,b){return ia(a,b,n)}function x(a,b){return ia(a,b,l)}
function ja(a){return a*a*a*a}function ka(a){return-(--a*a*a*a-1)}function la(a){const b=ea(ha(a));a/=fa(10,b);return(1>a?1:2>a?2:5>a?5:10)*fa(10,b)}function z(a){return"Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split(" ")[a]||"Unknown"}function ma(a,{qa:b=!1}={}){const c=a.getHours();a=String(a.getMinutes()).padStart(2,"0");return`${c%12||12}${b?`:${a}`:""} ${12>c?"A":"P"}M`};const {floor:na}=Math;function A(a){return{x:x(a.a,a=>a.x),y:x(a.a,a=>a.y)}}function B(a){return{x:w(a.a,a=>a.x),y:w(a.a,a=>a.y)}}
function oa(a,b,c){if(!a.a.length||b===c)return[];var d=pa(b,a.a,(c,d)=>{d=a.a[d-1];return c>=b&&(!d||d.x<b)});-1===d&&(d=0);const e=a.a.slice(d);var f=pa(c,e,(a,b)=>{b=e[b+1];return a<=c&&(!b||b.x>c)});if(-1===f){var g=a.a.length-1;f=c>a.a[g].x?g:d}else f=d+f;g=a.a.slice(d,f+1);const h=a.a[d];h.x!==b&&(d=a.a[d-1])&&g.unshift(ca(d,b,h));d=a.a[f];d.x===c||d===h&&h.x>c||(f=a.a[f+1])&&g.push(ca(d,c,f));return g}class qa{constructor(a,b,c){this.name=a;this.color=b;this.a=c}}
function pa(a,b,c){let d=0,e=b.length-1,f=na((d+e)/2),g;for(;b[f]&&!(g=c(b[f].x,f))&&d<e;)a<b[f].x?e=f-1:d=f+1,f=na((d+e)/2);return g?f:-1};const {min:ra,max:sa}=Math;function C(a){return"active"===a.R}function ta(a){throw Error(`Invalid state ${a.R}`);}
class D{constructor(a,b,c,d=p,e=p,f=p,g=p){this.c=a;this.b=b;this.l={["linear"]:q,["ease-in"]:ja,["ease-out"]:ka}[c];this.i=d;this.h=e;this.j=f;this.g=g;this.f=NaN;this.a=[];this.R="pending"}start(){C(this)&&ta(this);let a;const b=c=>{a||(a=c);const d=ra(c-a,this.b);this.a=this.c.map(a=>{const b=a.J-a.from,c=a.from+b*this.l(d/this.b);return 0<b?ra(c,a.J):sa(c,a.J)});this.i(this.a);d<this.b?this.f=requestAnimationFrame(b):(this.R="complete",this.h());this.j()};this.f=requestAnimationFrame(b);this.a=
this.c.map(a=>a.from);this.R="active"}stop(){C(this)||ta(this);cancelAnimationFrame(this.f);this.R="pending";this.a=[];this.g()}};const {ceil:ua,floor:E,min:va}=Math;function F(a){a.a.setTransform(1,0,0,1,0,0);a.a.clearRect(0,0,a.O,a.h);a.a.translate(a.A*a.c*-1,a.v*a.f);wa(a);xa(a);ya(a);if(a.H===a.G||isNaN(a.l)&&isNaN(a.o))a.a.font="20px Arial, Helvetica, Verdana, sans-serif",a.a.textBaseline="middle",a.a.textAlign="center",a.a.fillStyle=a.W,a.a.fillText(a.ja,a.O/2,a.h/2)}
function G(a,b){a.C.includes(b)||a.C.push(b);a.D.has(b)||a.D.set(b,0);var c=isNaN(a.H)||isNaN(a.G)?b.a:oa(b,a.H,a.G);a.B.set(b,c);const {x:d,y:e}=A(b);if(isNaN(a.l)||d<a.l)a.l=d;if(isNaN(a.M)||e<a.M)a.M=e;const {x:f,y:g}=B(b);if(isNaN(a.o)||f>a.o)a.o=f;if(isNaN(a.L)||g>a.L)a.L=g;c=x(a.B.get(b),a=>a.y);if(isNaN(a.j)||c<a.j)a.j=c;c=w(a.B.get(b),a=>a.y);if(isNaN(a.i)||c>a.i)a.i=c;c=[{from:a.D.get(b),J:1}];c=new D(c,350,"ease-out",([c])=>{a.D.set(b,c)},()=>{a.F.delete(b)},()=>{F(a)});const h=a.F.get(b);
h&&C(h)&&h.stop();a.F.set(b,c)}function za(a){a.g&&(a.g.stop(),a.g=null);Array.from(a.F.values()).forEach(a=>{C(a)&&a.stop()})}function Aa(a){a.C.length=0;a.N.length=0;a.B.clear();a.D.clear();a.F.clear()}
function Ba(a,b){var c=a.C.filter(c=>c!==b&&!a.N.includes(c)),d=c.map(b=>a.B.get(b));const {x:e,y:f}=A(b);if(e===a.l||f===a.M){var g=c.map(a=>A(a));const b=x(g,({x:a})=>a);b!==a.l&&(a.l=b);g=x(g,({y:a})=>a);g!==a.M&&(a.M=g)}const {x:h,y:m}=B(b);if(h===a.o||m===a.L)c=c.map(a=>B(a)),g=w(c,({x:a})=>a),g!==a.o&&(a.o=g),c=w(c,({y:a})=>a),c!==a.L&&(a.L=c);x(a.B.get(b),a=>a.y)===a.j&&(c=d.map(a=>x(a,a=>a.y)),c=x(c,q),c!==a.j&&(a.j=c));w(a.B.get(b),a=>a.y)===a.i&&(d=d.map(a=>w(a,a=>a.y)),d=w(d,q),d!==a.i&&
(a.i=d));d=[{from:a.D.get(b),J:0}];d=new D(d,350,"ease-in",([c])=>{a.D.set(b,c)},()=>{a.C.splice(a.C.indexOf(b),1);a.N.splice(a.N.indexOf(b),1);a.D.delete(b);a.B.delete(b);a.F.delete(b)},()=>{F(a)},()=>{a.N.splice(a.N.indexOf(b),1)});(c=a.F.get(b))&&C(c)&&c.stop();isNaN(a.l)&&isNaN(a.o)?(za(a),Aa(a)):(a.F.set(b,d),a.N.push(b))}function Ca(a){a.s.length=0;a.T=NaN;a.P.clear();a.b.length=0;a.m.clear()}
function Da(a){za(a);Aa(a);Ca(a);a.O=NaN;a.h=NaN;a.A=NaN;a.v=NaN;a.l=NaN;a.M=NaN;a.H=NaN;a.j=NaN;a.c=NaN;a.f=NaN;a.o=NaN;a.L=NaN;a.G=NaN;a.i=NaN;a.w=NaN;a.u=NaN}function H(a,b){var c=a.c;return n(l(a.c+(b-a.V)/a.A,a.w),c)}function Ea(a,b){var c=a.f;return n(l(a.f+(a.h-a.K-b)/a.v,a.u),c)}function I(a,b){return a.V+a.A*(b-a.c)}function Fa(){var a=J;return{start:isNaN(a.H)?a.l:a.H,end:isNaN(a.G)?a.o:a.G}}
function Ga(a,b,c){a.H=b;a.G=c;a.j=NaN;a.i=NaN;a.C.forEach(d=>{var e=oa(d,b,c);a.B.set(d,e);if(!a.N.includes(d)){d=x(e,a=>a.y);e=w(e,a=>a.y);if(isNaN(a.j)||d<a.j)a.j=d;if(isNaN(a.i)||e>a.i)a.i=e}})}
function L(a,b,c){const d="x"===c?a.Z:a.$;if("date"===d)b=new Date(b),a="x"===c?a.T:(a.u-a.f)/a.b.length,a=1<=a/31104E6?`${b.getFullYear()}`:1<=a/2592E6?`${b.getFullYear()} ${z(b.getMonth())}`:1<=a/864E5?`${z(b.getMonth())} ${b.getDate()}`:1<=a/36E5?`${z(b.getMonth())} ${b.getDate()} ${ma(b)}`:1<=a/6E4?`${ma(b,{qa:!0})}`:1<=a/1E3?`${b.getMinutes()}:${String(b.getSeconds()).padStart(2,"0")}`:b.toString();else if("compact"===d){a=b;for(c=0;1E3<=a;)a/=1E3,c++;a=Number(a.toFixed(1))+["","K","M","B","T"][c]}else a=
String(b);return a}function Ha(a){a.A=(a.O-a.V-a.ka)/(a.w-a.c)}function Ia(a){a.v=(a.h-a.Y-a.K)/(a.u-a.f)}
function Ja(a){var b=isNaN(a.H)?a.l:a.H,c=isNaN(a.G)?a.o:a.G;let d=a.T;if(d){const e=(c-b)/d;e?e>a.I?d*=2:e<a.I-2&&(d/=2):d=NaN}else d=(c-b)/a.I;if(d){a.c=b;a.w=c;Ha(a);a.T!==d&&(a.T=d,a.P.clear());b=(a.l-a.c)%d;var e=(a.w-a.c)/d;for(a.s=[a.c+b];a.s[a.s.length-1]<a.w+b;)c=a.c+b+a.s.length*d,a.s.push(c),a.P.delete(c);e<a.I-1&&a.s.slice().forEach(b=>{const c=b+d/2;c<a.w&&(a.s.splice(a.s.indexOf(b),1,b,c),a.P.set(c,a.I-1-e))})}else a.c=NaN,a.w=NaN,a.A=NaN,a.s=[],a.T=NaN,a.P.clear()}
function Ka(a){var b=isNaN(a.j)?a.M:a.j,c=isNaN(a.i)?a.L:a.i;let d=(c-b)/a.I;if(d){var e="nice"===a.na;if(e){d=la(d);const e=ua(c/d)-E(b/d);e>a.I&&(d=la(e*d/a.I))}var f=e?E(b/d)*d:b,g=e?ua(c/d)*d:c;if(isNaN(a.f)||isNaN(a.u))for(a.f=f,a.u=g,Ia(a),a.b=[a.f];a.b[a.b.length-1]<a.u;)a.b.push(a.f+a.b.length*d);else if(e=a.g&&a.g.c,b=a.g&&a.g.a,c=e?e[0].J:a.f,e=e?e[1].J:a.u,f!==c||g!==e){for(var h=a.b.slice(),m=[f];m[m.length-1]<g;)m.push(f+m.length*d);a.b=Array.from(new Set([...h,...m].sort((a,b)=>a-b)));
a.b.forEach(b=>{a.m.has(b)||(m.includes(b)&&a.m.set(b,0),h.includes(b)&&a.m.set(b,1))});var t=new Map(a.m);b=[{from:b?b[0]:c,J:f},{from:b?b[1]:e,J:g},{from:0,J:1}];a.g&&a.g.stop();a.g=new D(b,350,"linear",([b,c,d])=>{a.f=b;a.u=c;a.v=(a.h-a.Y-a.K)/(c-b);a.b.forEach(b=>{const c=t.get(b);m.includes(b)?a.m.set(b,c+d):h.includes(b)&&a.m.set(b,c-d)})},()=>{a.g=null;a.m.clear();for(a.b=[f];a.b[a.b.length-1]<g;)a.b.push(f+a.b.length*d)},()=>{F(a)})}}else a.f=NaN,a.u=NaN,a.v=NaN,a.b=[],a.m.clear()}
function M(a){Ja(a);Ka(a);a.g&&"pending"===a.g.R&&a.g.start();Array.from(a.F.values()).forEach(a=>{"pending"===a.R&&a.start()});F(a)}function wa(a){a.a.lineWidth=1;if("none"!==a.$){const b=a.A*a.c;a.b.forEach(c=>{const d=a.h-a.K-a.v*c;c=a.m.has(c)?a.m.get(c):1;a.a.strokeStyle=v(a.ga,c);a.a.beginPath();a.a.moveTo(b,d);a.a.lineTo(b+a.O,d);a.a.stroke()})}}
function xa(a){a.a.lineCap="round";a.a.lineJoin="round";a.a.lineWidth=a.U;a.C.forEach(b=>{const c=a.D.get(b),d=a.B.get(b);let e;a.a.beginPath();d.forEach((b,c)=>{const d=a.V+a.A*b.x;b=a.h-a.K-a.v*b.y;e&&E(e)===E(d)||(0===c?a.a.moveTo(d,b):a.a.lineTo(d,b),e=d)});a.a.strokeStyle=v(b.color,c);a.a.stroke()})}
function ya(a){a.a.font="15px Arial, Helvetica, Verdana, sans-serif";if("none"!==a.Z){const b=a.h-a.v*a.f-10,c=a.O/a.s.length,d=a.c===a.l,e=a.w===a.o;a.s.forEach(f=>{const g=a.A*f,h=L(a,f,"x");f=a.P.has(f)?a.P.get(f):1;a.a.textAlign=d?"start":e?"end":"center";if(a.la){const d=Array(h.length).fill("\u2588").join(""),e=a.a.measureText(h).width;a.a.fillStyle=a.X;a.a.fillText(d,g,b,va(e,c))}a.a.fillStyle=v(a.W,f);a.a.fillText(h,g,b,c)})}if("none"!==a.$){const b=a.A*a.c;a.b.forEach(c=>{const d=a.h-a.K-
a.v*c-10,e=L(a,c,"y");c=a.m.has(c)?a.m.get(c):1;a.a.textAlign="start";if(a.ma){const f=Array(e.length).fill("\u2588").join(""),g=a.a.measureText(e).width;a.a.fillStyle=v(a.X,c);a.a.fillText(f,b,d,g)}a.a.fillStyle=v(a.W,c);a.a.fillText(e,b,d)})}}
class O{constructor(a,{ea:b="decimal",wa:c=!1,fa:d="decimal",sa:e="extremum",ra:f=!1,da:g=0,aa:h=0,ha:m=0,ia:t=0,ba:K=1,pa:y=10,ua:N="#000",va:u="#000",ta:Za="#000",oa:$a=""}={}){this.S=a;this.a=a.getContext("2d");this.Y=g;this.K=h;this.V=m;this.ka=t;this.U=K;this.I=y;this.ga=N;this.W=u;this.X=Za;this.ja=$a;this.C=[];this.N=[];this.B=new Map;this.D=new Map;this.F=new Map;this.s=[];this.Z=b;this.la=c;this.T=NaN;this.P=new Map;this.b=[];this.$=d;this.na=e;this.ma=f;this.m=new Map;this.g=null;this.u=
this.w=this.i=this.G=this.L=this.o=this.f=this.c=this.j=this.H=this.M=this.l=this.v=this.A=this.h=this.O=NaN}resize(){this.O=this.S.parentNode.offsetWidth;this.h=this.S.parentNode.offsetHeight;this.S.width=this.O;this.S.height=this.h;Ha(this);Ia(this)}};function La(a,b){for(;a.a.firstChild;)a.a.removeChild(a.a.firstChild);b.forEach(({title:b,value:d,color:e})=>{const c=r("label__item");d=r("label__item-value",d);b=r("label__item-title",b);c.style.color=e;c.appendChild(d);c.appendChild(b);a.a.appendChild(c)})}class Ma{constructor(a){this.b=a;this.b.classList.add("label");this.c=r("label__title");this.a=r("label__items");this.b.appendChild(this.c);this.b.appendChild(this.a)}};const {abs:Na}=Math;function Oa(){var a=P,b=J;a.a&&(a.a.removeEventListener("mousemove",a.l),a.a.removeEventListener("mouseleave",a.j),a.a.removeEventListener("touchstart",a.m));a.a=b.S.parentElement;a.a.addEventListener("mousemove",a.l);a.a.addEventListener("mouseleave",a.j);a.a.addEventListener("touchstart",a.m);a.b=b}function Pa(a){a.g.forEach(b=>{a.a.removeChild(b)});a.g.length=0}
function Q(a){a.g.length&&(Pa(a),a.a.contains(a.f)&&a.a.removeChild(a.f),a.a.contains(a.c)&&a.a.removeChild(a.c))}function Qa(a,b){const c=a.b.Y,d=a.b.K;a.f.style.left=`${b}px`;a.f.style.top=`${c}px`;a.f.style.height=`${a.a.offsetHeight-c-d}px`;a.a.appendChild(a.f)}
function Ra(a,b,c,d){c="date"===a.b.Z?(new Date(c.x)).toLocaleDateString("en-us",{weekday:"short",month:"short",day:"numeric",hour:"numeric",minute:"numeric"}):L(a.b,c.x,"x");d=Array.from(d.entries()).sort((a,b)=>b[1].y-a[1].y).map(([b,c])=>({title:b.name,color:b.color,value:L(a.b,c.y,"y")}));a.i.c.textContent=c;La(a.i,d);a.a.appendChild(a.c);d=a.a.offsetWidth;c=a.c.offsetWidth;b=b+c+10<=d?b+10:c+10<=b?b-c-10:n(l(b-c/2,d),0);a.c.style.left=`${b}px`}
class Sa{constructor(){this.b=this.a=null;this.g=[];this.f=r("cursor__ruler");this.c=r();this.i=new Ma(this.c);this.h=NaN;this.l=this.s.bind(this);this.j=this.o.bind(this);this.m=this.u.bind(this)}s(a){var b=this.a.getBoundingClientRect(),c=a.clientX-b.left;a=a.clientY-b.top;b=this.h||this.b.U;const d=H(this.b,c-b),e=H(this.b,c+b),f=Ea(this.b,a),g=new Map;this.b.C.forEach(a=>{const b=a.a.find(a=>a.x>=d&&a.x<=e);b&&!b.ca&&g.set(a,b)});Q(this);if(g.size){let a;Array.from(g.entries()).forEach(([b,c])=>
{{const a=r("cursor__marker");a.style.borderColor=b.color;a.style.left=`${I(this.b,c.x)}px`;b=this.b;a.style.top=`${b.h-b.K-b.v*(c.y-b.f)}px`;this.a.appendChild(a);this.g.push(a)}if(!a||Na(f-c.y)<Na(f-a.y))a=c});c=I(this.b,a.x);Qa(this,c);Ra(this,c,a,g)}this.h=NaN}u(a){const b=this.b.S;if(a=Array.from(a.touches).find(a=>a.target===b))this.h=a.radiusX||NaN}o(){Q(this)}};const {max:Ta,round:Ua}=Math;function R(a,b){a.h=b;a.i.style.width=`${b}px`}function S(a,b){a.m=b;a.l.style.width=`${b}px`}function T(a,b){const c=b<a.a.offsetWidth-(a.g+a.j);a.f=b;a.c.style.width=`${b}px`;a.c.classList.toggle("_draggable",c)}function Va(a,b){var c=U;const d=c.a.offsetWidth;R(c,a-c.g);S(c,d-b-c.j);T(c,b-a)}function Wa(){var a=U;const b=a.h+a.g;return{start:b,end:b+a.f}}
class Xa{constructor(a){this.a=a;this.b=p;this.m=this.j=this.f=this.g=this.h=NaN;this.a.classList.add("zoombar");this.o=r("zoombar__grip");this.i=r("zoombar__overlay");this.c=r("zoombar__pan");this.s=r("zoombar__grip");this.l=r("zoombar__overlay");this.a.appendChild(this.i);this.a.appendChild(this.o);this.a.appendChild(this.c);this.a.appendChild(this.s);this.a.appendChild(this.l);this.g=this.o.offsetWidth;this.j=this.s.offsetWidth;Ya(this.a,this.o,this.u.bind(this));Ya(this.a,this.s,this.C.bind(this));
Ya(this.a,this.c,this.A.bind(this),this.w.bind(this),this.B.bind(this));this.i.addEventListener("click",this.v.bind(this));this.l.addEventListener("click",this.D.bind(this))}u(a){const b=this.f-a;0<=b&&(R(this,this.h+a),T(this,b),this.b())}C(a){const b=this.f+a;0<=b&&(S(this,this.m-a),T(this,b),this.b())}A(a){let b=this.h+a;a=this.m-a;0>b?(a+=b,b=0):0>a&&(b+=a,a=0);R(this,b);S(this,a);this.b()}w(){this.c.classList.add("_dragging")}B(){this.c.classList.remove("_dragging")}v(a){const b=this.i.getBoundingClientRect();
a=a.clientX-b.left-this.g;a-=this.f/2;a=Ta(a,0);R(this,a);S(this,this.m+b.width-a);this.b()}D(a){const b=this.l.getBoundingClientRect();a=b.right-a.clientX-this.j;a-=this.f/2;a=Ta(a,0);S(this,a);R(this,this.h+b.width-a);this.b()}}function ab(a,b){return a.touches?(a=Array.from(a.touches).find(a=>a.target===b))?a.clientX:NaN:a.clientX}
function Ya(a,b,c=p,d=p,e=p){let f,g,h,m,t;const K=c=>{c=ab(c,b);f=a.getBoundingClientRect();g=b.getBoundingClientRect();h=c-g.left;m=c-f.left;a.addEventListener("mousemove",y);a.addEventListener("touchmove",y);a.addEventListener("mouseup",u);a.addEventListener("mouseleave",u);a.addEventListener("touchend",u);t&&(clearTimeout(t),t=void 0);a.addEventListener("click",N,!0);d()},y=a=>{a=ab(a,b)-f.left;if(a>=h&&a+g.width-h<=f.width){const b=a-m;b&&c(Ua(b));m=a}},N=a=>{a.stopPropagation()},u=()=>{a.removeEventListener("mousemove",
y);a.removeEventListener("touchmove",y);a.removeEventListener("mouseup",u);a.removeEventListener("mouseleave",u);a.removeEventListener("touchend",u);t=setTimeout(()=>{a.removeEventListener("click",N,!0)},100);m=h=g=f=void 0;e()};b.addEventListener("mousedown",K);b.addEventListener("touchstart",K)};function bb(a){a.c.addEventListener("click",()=>{a.b=!a.b;a.a.classList.add("_animated");cb(a);a.f()})}function cb(a){a.a.classList.toggle("_checked",a.b);a.a.classList.toggle("_unchecked",!a.b)}function db(a,b){a.f=b}
class eb{constructor(a,b,c,d=!0){this.a=a;this.h=b;this.g=c;this.b=d;this.f=p;this.a.classList.add("checkbox");this.c=r("checkbox__icon");this.c.style.borderColor=this.g;this.c.appendChild(r("checkbox__mark"));this.a.appendChild(this.c);this.a.appendChild(r("checkbox__text",this.h));bb(this);cb(this)}};const V=window.matchMedia("only screen and (max-width: 480px) and (orientation: portrait)"),J=new O(document.querySelector("#zoom-chart-canvas"),{ea:"date",fa:"compact",sa:"nice",ra:!0,da:30,aa:40,pa:V.matches?3:5,ba:V.matches?2:3,oa:"No data"}),W=new O(document.querySelector("#overview-chart-canvas"),{ea:"none",fa:"none",da:10,aa:10,ha:15,ia:15,ba:V.matches?1:2}),P=new Sa,fb=document.querySelector("#zoombar"),U=new Xa(fb),gb=document.querySelector("#title"),X=document.querySelector("#legend"),hb=
document.querySelector("#select"),ib=document.querySelector("#theme-switch-button"),Y=[],jb=[];let Z=window.localStorage.getItem("telegram-contest-chart_theme")||"day";
window.addEventListener("load",()=>{fetch("data.json").then(a=>a.json()).then(a=>{a.forEach(a=>{const b=a.columns.find(a=>"x"===a[0]).slice(1),d=a.columns.filter(a=>a[0].startsWith("y")).map(([c,...d])=>new qa(a.names[c],a.colors[c],d.map((a,c)=>new da(b[c],a))));Y.push(d)})}).finally(()=>{Oa();U.b=kb;ib.addEventListener("click",()=>{lb("day"===Z?"night":"day")});V.addListener(()=>{var a=J;a.I=V.matches?3:5;a.c=NaN;a.f=NaN;a.w=NaN;a.u=NaN;Ca(a);J.U=V.matches?2:3;W.U=V.matches?1:2;mb()});window.addEventListener("resize",
mb);window.addEventListener("orientationchange",mb);Y.forEach(a=>{const b=r("select__chart"),c=document.createElement("canvas"),d=new O(c,{ea:"none",fa:"none",da:5,aa:5,ha:5,ia:5,ba:1});a.forEach(a=>{G(d,a)});b.appendChild(c);b.addEventListener("click",()=>nb(a));hb.appendChild(b);jb.push(d)});jb.forEach(a=>{a.resize();M(a)});lb(Z);Y[0]&&nb(Y[0])})});
function lb(a){document.body.classList.remove(`_${Z}`);document.body.classList.add(`_${a}`);window.localStorage.setItem("telegram-contest-chart_theme",Z=a);ib.textContent={["day"]:"Switch to Night Mode",["night"]:"Switch to Day Mode"}[a];J.ga={["day"]:"#dfe7eb",["night"]:"#394959"}[a];J.W={["day"]:"#a9b3b9",["night"]:"#4c5f6f"}[a];J.X={["day"]:"#ffffff",["night"]:"#232f3d"}[a];M(J)}
function nb(a){Q(P);Da(J);for(Da(W);X.firstChild;)X.removeChild(X.firstChild);a.forEach(a=>{const b=r(),c=new eb(b,a.name,a.color);db(c,()=>{c.b?(G(J,a),G(W,a)):(Ba(J,a),Ba(W,a));M(W);const b=Wa();Ga(J,H(W,b.start),H(W,b.end));M(J)});G(J,a);G(W,a);X.appendChild(b)});W.resize();M(W);J.resize();M(J);Va(15,fb.offsetWidth-15);const b=Y.indexOf(a);Array.from(hb.childNodes).forEach((a,d)=>{a.classList.toggle("_active",d===b)});gb.textContent=`Chart #${b+1}`}
function mb(){[J,W,...jb].forEach(a=>{a.resize();M(a)});const a=Fa();Va(I(W,a.start),I(W,a.end));Q(P)}function kb(){var a=Wa();const b=H(W,a.start);a=H(W,a.end);Ga(J,b,a);M(J);Q(P)};
